### PR TITLE
Kotlin-1.4.10

### PR DESCRIPTION
**Pull request by antonioseric**

### CODE REVIEW

**Comment by tailsu** [comment]
Hi guys, how can we expedite this PR?

We have project dependencies that have migrated to Kotlin-1.4 already and this issue is preventing us from upgrading.

**Comment by tailsu** [comment]
I would like to politely cite an excerpt from Microsoft's own documentation on [Resolving incompatible package errors](https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution#resolving-incompatible-package-errors)

> To resolve incompatibilities, do one of the following:
> * ...
> * Contact the author of the packages and work with them to add support for your chosen framework. Each package listing page on nuget.org has a Contact Owners link for this purpose.

I've been looking for three days now for a way to integrate in my project both the latest Kotlin and another library that references this package. I wasn't able to do it, so my last resort is to ask you guys and gals to try and push this PR forward.

Thank you.

**Comment by cybvitthal** [comment]
Hey @mattleibow, Are you guys planning to include one of `Kotlin-1.4.*` PR in next release?

**Comment by mattleibow** [comment]
Just letting everyone know that both v1.4 versions are out!

**Pull request merged**
