### PR TITLE
[Xamarin.Android.Glide] add multitargeting for .NET 6

### PR DESCRIPTION
**Pull request by jonathanpeppers**
* Install latest .NET 6 & stable Xamarin.Android on CI
* Use Xamarin.Legacy.Sdk.
* Build with `dotnet build`
* Use `[assembly: AssemblyMetadata("IsTrimmable", "True")]`
* Use the same pattern as AndroidX, putting `.aar`/`.jar` files loose inside the NuGet package
* Set legacy compatibility properties mentioned here:

https://github.com/xamarin/xamarin-android/blob/5f408ebb22df51b598c62f776ee0f82f92661b58/Documentation/guides/OneDotNetBindingProjects.md

This also updates any AndroidX dependencies so that they are using the
new versions that *also* multitarget for .NET 6.

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
I need to manually verify and test these packages.

It is concerning the file size is so different here:

image

**Comment by jpobst** [comment]
The `monoandroid10.0` `.dll` has the `.aar` embedded in it.  The `net6.0-android30.0` `.dll` does not.

image

**Comment by jonathanpeppers** [comment]
Yeah, I think this needs some custom `.targets` now. We don't want the `.aar` file in here twice, so we need to follow the pattern AndroidX has where the `.aar` file is included in the `.nupkg` file.

I'll probably come back to this later, some other stuff has come up.

**Comment by moljac** [comment]
Glide is new dependency of some of GPS-FB-MLKit artifacts and it has `MonoAndroid10.0` TFM. 

Adding multitargeting and `MonoAndroid9.0` TFM 

https://github.com/xamarin/XamarinComponents/pull/1270

https://github.com/xamarin/XamarinComponents/pull/1271

**Comment by jonathanpeppers** [comment]
I manually tested the packages here: https://github.com/jonathanpeppers/glidex/compare/test-glide-update

The file layout is now:
```
> 7z l .\packages\Xamarin.Android.Glide.4.12.0.1.nupkg

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 1082782 bytes (1058 KiB)

Listing archive: .\packages\Xamarin.Android.Glide.4.12.0.1.nupkg

--
Path = .\packages\Xamarin.Android.Glide.4.12.0.1.nupkg
Type = zip
Physical Size = 1082782

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2021-09-15 18:01:48 .....          515          288  _rels\.rels
2021-09-15 18:01:48 .....         2834          729  Xamarin.Android.Glide.nuspec
2021-09-15 18:01:20 .....      1062912       215522  lib\monoandroid10.0\Xamarin.Android.Glide.dll
2021-09-15 18:01:20 .....          146           94  lib\monoandroid10.0\Xamarin.Android.Glide.xml
2021-09-15 18:01:36 .....      1074688       220208  lib\net6.0-android31.0\Xamarin.Android.Glide.dll
2021-09-15 18:01:36 .....          146           94  lib\net6.0-android31.0\Xamarin.Android.Glide.xml
2021-09-15 18:00:36 .....       640219       640101  aar\glide.aar
2021-09-15 17:46:38 .....          235          144  build\MonoAndroid10.0\Xamarin.Android.Glide.targets
2021-09-15 17:46:38 .....          235          144  buildTransitive\MonoAndroid10.0\Xamarin.Android.Glide.targets
2021-09-15 17:46:38 .....          235          144  build\net6.0-android31.0\Xamarin.Android.Glide.targets
2021-09-15 17:46:38 .....          235          144  buildTransitive\net6.0-android31.0\Xamarin.Android.Glide.targets
2021-09-15 17:46:38 .....         5468         2288  THIRD-PARTY-NOTICES.txt
2021-09-15 18:01:50 .....          721          234  [Content_Types].xml
2021-09-15 18:01:50 .....          645          380  package\services\metadata\core-properties\86abf10194fb49b688a09cae84233cc1.psmdcp
------------------- ----- ------------ ------------  ------------------------
2021-09-15 18:01:50            2789234      1080514  14 files
```

**Review by moljac — APPROVED** [review]
LGTM

**Comment by jpobst** [comment]
> Glide is new dependency of some of GPS-FB-MLKit artifacts and it has `MonoAndroid10.0` TFM.
> 
> Adding multitargeting and `MonoAndroid9.0` TFM
> 
> #1270
> 
> #1271

Per this comment, I don't think we can remove `MonoAndroid9.0`.

Also, what do we need to get CI to run on this? Bump the version number?  (cc @moljac)

I would like a chance to examine the final NuGet package before we merge since there are a lot of changes to this.

**Comment by jonathanpeppers** [comment]
CI ran previously... because I downloaded artifacts...

**Comment by moljac** [comment]
> Also, what do we need to get CI to run on this? Bump the version number? (cc @moljac)

for publishing?

tagging. But leave it to me. Tags in XC repo are messy and I never got to clean them up.

**Comment by moljac** [comment]
> Per this comment, I don't think we can remove `MonoAndroid9.0`.

Yes. This is why I wrote that.  
OTOH it might take a while for google to make some dependencies releases, until then `MonoAndroid9.0` might become obsolete.

`Directory.Build.props` has `MonoAndroid9.0`, so it should be OK if I'll be necessary to add those dependencies.

> I would like a chance to examine the final NuGet package before we merge since there are a lot of changes to this.

Now I see `MonoAndroid9.0` is not packaged.

**Review by jpobst — APPROVED** [review]
Not sure why the CI wasn't showing up in GitHub.  🤷 

Packages look good.  Will have to bump version numbers if you want to release new packages with these changes: https://github.com/xamarin/XamarinComponents/pull/1271/files.

**Comment by jonathanpeppers** [comment]
@moljac would you be able to release the Glide packages later this week? Thanks!

**Comment by moljac** [comment]
> @moljac would you be able to release the Glide packages later this week? Thanks!

Tagged. Waiting for CI. By the time you get up I think I will publish it.

**Comment by jonathanpeppers** [comment]
The latest release is working fine: https://github.com/dotnet/maui/pull/2563

**Pull request merged**
