### PR TITLE
ML Kit Xamarin.Android bindings

### LINKED ISSUE #932: MLKit missing?
It seems that we have a bindings library for Firebase.ML, but no bindings library for Firebase.MLKit for Android at least. [Here is the iOS equivalent](https://www.nuget.org/packages/Xamarin.Firebase.iOS.MLKit.Vision/) of the package i'm looking for. Am i missing something or does Firebase.MLKit have a bindings library for iOS, but not Android?

### PR DESCRIPTION
**Pull request by moljac**
initial commit

ML Kit is on device SDK for machine learning. Originally it was part of the GPS-FB, but as of 202007 it is separate artifact `groupid`.

artifacts (v.16.0.0):

*   `barcode-scanning`
*   `common`
*   `face-detection`
*   `barcode`
*   `image-labeling`
*   `image-labeling-automl`
*   `image-labeling-comon`
*   `image-labeling-custom`
*   `language-id`
*   `linkfirebase`
*   `object-detection`
*   `object-detection-common`
*   `object-detection-custom`
*   `smart-reply`
*   `translate`
*   `vision-common`
*   `vision-internal-vkp`

### CODE REVIEW

**Review by grendello — APPROVED** [review]

**Comment by supremedictator** [comment]
@moljac do you have a timeline for when this will be merged into the master branch,
It is becoming critical for application to have bundle version of the mlkit barcode scanning in Xamarin

**Comment by moljac** [comment]
@supremedictator Doing my best...

**Comment by supremedictator** [comment]
@moljac I appreciate the effort, thanks.

**Comment by ccitl** [comment]
Is there any update on the progress of this?
Thanks

**Comment by ccitl** [comment]
Is development on this branch still active?

**Comment by carbonete** [comment]
Is this active ?

**Comment by Yuliya-Fedorenko** [comment]
We are also interested in this bindings for barcode scanning functionality in xamarin forms android app...

**Comment by carbonete** [comment]
This still active ?

Thanks for work

**Comment by moljac** [comment]
Moved to GSP-FB repo

**Comment by lt-gerjan** [comment]
@moljac Where did this PR land now? Do you have a link? Would be really nice to have bindings for ML Kit...

**Comment by moljac** [comment]
@gerjandev 
Why don't you check nuget.org for the binaries/packages...

GPS-FB means GooglePlayServices+Firebase, so here:

https://github.com/xamarin/GooglePlayServicesComponents

to be exact:

https://github.com/xamarin/GooglePlayServicesComponents/blob/master/config.json#L963-L1138

OK?

**Comment by lt-gerjan** [comment]
Yes, awesome. Big thanks and great work @moljac

**Comment by ederbond** [comment]
@moljac do you have any sample in Xamarin that shows how to use face-detection?
I'm particularly interested in how should I implement an `ImageAnalysis.IAnalyzer`

**Comment by moljac** [comment]
@ederbond 

> do you have any sample in Xamarin that shows how to use face-detection?

I wish.

> I'm particularly interested in how should I implement an ImageAnalysis.IAnalyzer

Try porting some samples. I have it on my list, but more important stuff keeps flowing in.

Q: why asking here. MLKit is in https://github.com/xamarin/GooglePlayServicesComponents

**Pull request closed without merging**
