### PR TITLE
[Xamarin.Build.Download] remove AndroidAarFixups

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Context: https://github.com/dotnet/runtime/issues/68734

A breaking chang in in .NET 7 has uncovered an issue when using
Xamarin.Build.Download:

    Renaming: AndroidManifest.xml to AndroidManifest.xml
    ...
    (_XamarinBuildDownloadCore target) ->
        /Users/runner/.nuget/packages/xamarin.build.download/0.11.0/buildTransitive/Xamarin.Build.Download.targets(52,3): error XBD001: Download failed. Please download https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-basement/17.6.0/play-services-basement-17.6.0.aar to a file called /Users/runner/Library/Caches/XamarinBuildDownload/playservicesbasement-17.6.0.aar.
        /Users/runner/.nuget/packages/xamarin.build.download/0.11.0/buildTransitive/Xamarin.Build.Download.targets(52,3): error XBD001: Download failed. Please download https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-tasks/17.2.1/play-services-tasks-17.2.1.aar to a file called /Users/runner/Library/Caches/XamarinBuildDownload/playservicestasks-17.2.1.aar.
        /Users/runner/.nuget/packages/xamarin.build.download/0.11.0/buildTransitive/Xamarin.Build.Download.targets(52,3): error XBD001: Download failed. Please download https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-base/17.6.0/play-services-base-17.6.0.aar to a file called /Users/runner/Library/Caches/XamarinBuildDownload/playservicesbase-17.6.0.aar.
        /Users/runner/.nuget/packages/xamarin.build.download/0.11.0/buildTransitive/Xamarin.Build.Download.targets(52,3): error XBD001: Download failed. Please download https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-maps/17.0.1/play-services-maps-17.0.1.aar to a file called /Users/runner/Library/Caches/XamarinBuildDownload/playservicesmaps-17.0.1.aar.
    1 Warning(s)
    4 Error(s)

The exception is somewhat swallowed here, the underlying error is
something like:

    System.InvalidOperationException : An entry named 'AndroidManifest.xml' already exists in the archive.

This class had various "fixups" to workaround issues in
Xamarin.Android. Many of these issues have long since been fixed.

1. Removal of `aapt/AndroidManifest.xml`. Xamarin.Android has been
   handling this since ~Sept 2018:

https://github.com/xamarin/xamarin-android/commit/f6c3288dd5a7f82c178ef30ad25c11d475f1daf4

2. Removal of `internal_impl-*.jar`. Xamarin.Android has been handling
   this since ~Feb 2018:

https://github.com/xamarin/xamarin-android/commit/6a8ea2bbdbad65f1f46ba60a343506c92d1e0a1e

3. Replacement of `android:name=".SomeService"` as shorthand for
   `androidx.foo.SomeService` in the `androidx.foo` package. The use
   of `manifest-merger` solves this issue completely. This setting is
   the default for .NET 6, and has been the default for AndroidX since
   ~July 2020:

https://github.com/xamarin/AndroidX/commit/c6c0e5033c825e0b13e5a5a0aa896dcafe43e6f6

### CODE REVIEW

**Comment by dellis1972** [comment]
Does this have the potential to break any existing customers ? If so I guess the work around would be to downgrade this package to an older version. I'm mainly thinking about people who turn manifest merger off since it is an overridable property.

**Comment by jonathanpeppers** [comment]
@dellis1972 I think we could probably release an update of Xamarin.Build.Download and not update the dependencies yet.

So keep this on the old version, for example:

https://github.com/xamarin/GooglePlayServicesComponents/blob/b97bb6bb9bfaaea9fa81210b1ef7d548b256a49f/source/GooglePlayServicesProject.cshtml#L297-L299

Then if something goes wrong, we can bring this file back -- and rewrite it so it works in .NET 7.

**Comment by jonathanpeppers** [comment]
The main thing is if Xamarin.Build.Download is fixing something -- we actually should fix Xamarin.Android so any library *not* using Xamarin.Build.Download would be able to work...

**Review by dellis1972 — APPROVED** [review]

**Review by moljac — APPROVED** [review]
LGTM

**Pull request merged**
