### PR TITLE
Update arcore to 1.29

### PR DESCRIPTION
**Pull request by softlion**
Update arcore to 1.29
Also fix an issue with the cake script, where changing the arcore version won't override already downloaded library files.

### CODE REVIEW

**Comment by nCastle1** [comment]
It appears I've duplicated this in #1317.

I would be able to close my PR if this PR was updated to uncomment `<attr path="/api/package[@name='com.google.ar.core']/class[@name='TrackableBase']" name="visibility">public</attr>` on line 12 of **Metadata.xml**. I've tested that change and confirmed it would resolve https://github.com/xamarin/XamarinComponents/issues/1305

**Comment by softlion** [comment]
Well i may have "duplicated" your pr too. I only needed the latest version of the android lib as the .26 has crashing issues with Anchors.
I'm also the author of the breaking change pr - mea culpa.

Are the changes i've just made in Additions.cs enough ?

**Comment by nCastle1** [comment]
I built this branch. With the changes to Additions.cs, `Plane` now implements `ITrackable`, solving the problem raised in #1305.

**Comment by nCastle1** [comment]
@softlion Is this ready for review? I see @moljac has reviewed these PRs in the past, but I don't see anything merged since 2021.

**Comment by softlion** [comment]
I have my own nuget, so feel free to merge or not. I don’t know who review, who owns, what the process is, how to become part of it,  and there is no way to contact anyone. So …

**Review by moljac — APPROVED** [review]

**Pull request merged**
