### PR TITLE
rxjava2-2.2.10 rxjava3-3.0.1

### LINKED ISSUE #1110: ReactiveX namespace not visible
I have added the Xamarin.Android.ReactiveX.RxJava 2.2.9 NuGet package to a Xamarin Android application.
I don't see the ReactiveX namespace. The (depency) ReactiveStreams namespace is available though.
I was hoping to use the package as a replacement for the Naxam.Android.RxJava2 package because I need Java 2.2.x support and the Naxam is 2.1.x

### PR DESCRIPTION
**Pull request by moljac**
Updates + fixes:

* io.reactivex.rxjava2:rxjava-2.2.10
* io.reactivex.rxjava2:rxkotlin-2.4.0

* io.reactivex.rxjava3:rxjava-3.0.1
* io.reactivex.rxjava3:rxkotlin-3.0.1

Fixes for: 

> XA1014: JAR library references with identical file names but different contents were found: rxjava.jar

https://github.com/xamarin/AndroidX/issues/277

should unblock: https://github.com/xamarin/AndroidX/issues/277

Fixes also:

https://github.com/xamarin/XamarinComponents/issues/1110

### CODE REVIEW

**Comment by moljac** [comment]
quite a lot of updates coming, but this is needed as template (fixes/changes for artifact names)

**Review by jpobst — APPROVED** [review]

**Review by jpobst — CHANGES_REQUESTED** [review]
It looks like some of the namespaces regressed back to `IO.Reactivex`:

[Xamarin.Android.ReactiveX.RxAndroid.dll.diff.txt](https://github.com/xamarin/XamarinComponents/files/6224378/Xamarin.Android.ReactiveX.RxAndroid.dll.diff.txt)

**Comment by moljac** [comment]
BuildAction was None

**Review by jpobst — APPROVED** [review]

**Pull request merged**
