### PR TITLE
Added CrossDownloadManager plugin

### PR DESCRIPTION
**Pull request by SimonSimCity**

### CODE REVIEW

**Comment by SimonSimCity** [comment]
Closes #20

**Comment by SimonSimCity** [comment]
This PR includes the new reference to the plugin. #20 still contained a version of this plugin that was not build up according to the rules for this repository.

**Comment by SimonSimCity** [comment]
Do you have time to merge it, or is there something I left out?

This plugin meets all requirements for a Plugin (thanks to @martijn00) and is available on NuGet and GitHub, like you can see in the `README.md`.

**Comment by jamesmontemagno** [comment]
@SimonSimCity awesome! I will have a bit of feedback on the GitHub page ;)

**Pull request merged**
