### PR TITLE
Moshi-1.13.0

### PR DESCRIPTION
**Pull request by 4brunu**
Updates Moshi to 1.13.0

### CODE REVIEW

**Comment by 4brunu** [comment]
@moljac I'm having the following error, but I don't know how to fix it.
```
       "/Users/user/Developer/XamarinComponents/Android/SquareMoshi/source/Square.Moshi.sln" (Restore target) (1) ->
       (Restore target) -> 
         /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(131,5): error : Package Xamarin.Kotlin.StdLib.Jdk8 1.6.0 is not compatible with monoandroid11.0 (MonoAndroid,Version=v11.0). Package Xamarin.Kotlin.StdLib.Jdk8 1.6.0 supports: [/Users/user/Developer/XamarinComponents/Android/SquareMoshi/source/Square.Moshi.sln]
       /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(131,5): error :   - monoandroid12.0 (MonoAndroid,Version=v12.0) [/Users/user/Developer/XamarinComponents/Android/SquareMoshi/source/Square.Moshi.sln]
       /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(131,5): error :   - net6.0-android31.0 (.NETCoreApp,Version=v6.0) [/Users/user/Developer/XamarinComponents/Android/SquareMoshi/source/Square.Moshi.sln]
```

Do you have any idea how to fix this?

**Comment by 4brunu** [comment]
@moljac I was able to fix the error, and now it builds on my machine.

The CI is failling because that macOS CI image doesn't have monodroid12 installed, which is a requirement of `Xamarin.Kotlin.StdLib.Jdk8 1.6.10` which is a dependency of Moshi.

So if I set monoandroid to less that 12, for example, 11, it show's the following error:
```
"/Users/user/Developer/XamarinComponents/Android/SquareMoshi/source/Square.Moshi.sln" (Restore target) (1) ->
(Restore target) -> 
  /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(131,5): error : Package Xamarin.Kotlin.StdLib.Jdk8 1.6.10 is not compatible with monoandroid11.0 (MonoAndroid,Version=v11.0). Package Xamarin.Kotlin.StdLib.Jdk8 1.6.10 supports: [/Users/user/Developer/XamarinComponents/Android/SquareMoshi/source/Square.Moshi.sln]
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(131,5): error :   - monoandroid12.0 (MonoAndroid,Version=v12.0) [/Users/user/Developer/XamarinComponents/Android/SquareMoshi/source/Square.Moshi.sln]
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(131,5): error :   - net6.0-android31.0 (.NETCoreApp,Version=v6.0) [/Users/user/Developer/XamarinComponents/Android/SquareMoshi/source/Square.Moshi.```sln]
```

So I'm not sure what we should do to fix this error.
Is it possible to update CI to have monodroid12 installed?

**Comment by moljac** [comment]
well

maybe this will help:

replace:

https://github.com/4brunu/XamarinComponents/blob/feature/moshi1.13.0/azure-pipelines.yml#L25

with

https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/5673868/d17-1/19b97b7614b275a84d9e38096bd1fe0e25a494d4/xamarin.android-12.2.0.4.pkg

not sure this will work, but let us try

**Comment by 4brunu** [comment]
It worked, CI is now passing, thanks 👍

**Review by moljac — APPROVED** [review]
LGTM

**Pull request merged**
