### PR TITLE
OkHttp-UrlConnection-4.9.2

### PR DESCRIPTION
**Pull request by 4brunu**
bump OkHttp UrlConnection bind 4.9.2
~~Depends on https://github.com/xamarin/XamarinComponents/pull/1283~~

### CODE REVIEW

**Comment by tranb3r** [comment]
@moljac This one is also stuck. Is it possible to fix it ? Thanks!

**Comment by tranb3r** [comment]
Hi @moljac 
Now that okhttp 4.9.2 has been published, could you please fix this PR ?
Thanks a lot!

**Comment by tranb3r** [comment]
@moljac Could you please at least tell me what is going on ?

**Comment by moljac** [comment]
@tranb3r Sorry, but no idea. I need to look into it, but am deep into moving template sets to GPS-FB-MLKit repo.

**Comment by moljac** [comment]
seems like new parameters were added to Azure pipeline templates (xcode: 13.0), but I might be wrong I am no AzureDevOps guru

**Comment by 4brunu** [comment]
CI is now passing, thanks 👍

**Review by tranb3r — APPROVED** [review]

**Review by moljac — APPROVED** [review]
LGTM

**Review by moljac — APPROVED** [review]

**Pull request merged**
