### PR TITLE
[XBD] Trigger GC if assembly is not writable in MergeResources

### PR DESCRIPTION
**Pull request by michd**
I'd like to preface this with a statement that I don't really imagine this will be merged as-is, as it's more of a workaround for an issue elsewhere in the build process.

---

Here is a typical excerpt of the build log we'd get before this workaround, this one on Windows:

```
C:\BuildAgent\work\52fe272bfade4750\packages\Xamarin.Build.Download.0.4.6\build\Xamarin.Build.Download.targets(93,3): error : The process cannot access the file 'C:\BuildAgent\work\52fe272bfade4750\packages\Xamarin.Android.Support.Annotations.25.3.1\lib\MonoAndroid70\Xamarin.Android.Support.Annotations.dll' because it is being used by another process.
C:\BuildAgent\work\52fe272bfade4750\packages\Xamarin.Build.Download.0.4.6\build\Xamarin.Build.Download.targets(93,3): error :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
C:\BuildAgent\work\52fe272bfade4750\packages\Xamarin.Build.Download.0.4.6\build\Xamarin.Build.Download.targets(93,3): error :    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
C:\BuildAgent\work\52fe272bfade4750\packages\Xamarin.Build.Download.0.4.6\build\Xamarin.Build.Download.targets(93,3): error :    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
C:\BuildAgent\work\52fe272bfade4750\packages\Xamarin.Build.Download.0.4.6\build\Xamarin.Build.Download.targets(93,3): error :    at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
C:\BuildAgent\work\52fe272bfade4750\packages\Xamarin.Build.Download.0.4.6\build\Xamarin.Build.Download.targets(93,3): error :    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
C:\BuildAgent\work\52fe272bfade4750\packages\Xamarin.Build.Download.0.4.6\build\Xamarin.Build.Download.targets(93,3): error :    at Xamarin.Build.Download.BaseXamarinBuildResourceRestore.MergeResources(IAssemblyResolver resolver, String originalAsmPath, String mergedAsmPath, String assemblyName, List`1 resourceItems)
```

The same issue on OS X:

```
/Users/ci/buildAgent/work/52fe272bfade4750/packages/Xamarin.Build.Download.0.4.5/build/Xamarin.Build.Download.targets(113,3): error : Sharing violation on path /Users/ci/buildAgent/work/52fe272bfade4750/packages/Xamarin.Android.Support.v7.AppCompat.25.1.1/lib/MonoAndroid70/Xamarin.Android.Support.v7.AppCompat.dll
/Users/ci/buildAgent/work/52fe272bfade4750/packages/Xamarin.Build.Download.0.4.5/build/Xamarin.Build.Download.targets(113,3): error :   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x001d8] in <ffb99659fc1c47faa4d5f883014d08aa>:0
/Users/ci/buildAgent/work/52fe272bfade4750/packages/Xamarin.Build.Download.0.4.5/build/Xamarin.Build.Download.targets(113,3): error :   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00000] in <ffb99659fc1c47faa4d5f883014d08aa>:0
/Users/ci/buildAgent/work/52fe272bfade4750/packages/Xamarin.Build.Download.0.4.5/build/Xamarin.Build.Download.targets(113,3): error :   at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
/Users/ci/buildAgent/work/52fe272bfade4750/packages/Xamarin.Build.Download.0.4.5/build/Xamarin.Build.Download.targets(113,3): error :   at Mono.Cecil.ModuleDefinition.GetFileStream (System.String fileName, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x0001c] in <d4dd94f3e5f74095b62543e88f18941d>:0
/Users/ci/buildAgent/work/52fe272bfade4750/packages/Xamarin.Build.Download.0.4.5/build/Xamarin.Build.Download.targets(113,3): error :   at Mono.Cecil.ModuleDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters) [0x00000] in <d4dd94f3e5f74095b62543e88f18941d>:0
/Users/ci/buildAgent/work/52fe272bfade4750/packages/Xamarin.Build.Download.0.4.5/build/Xamarin.Build.Download.targets(113,3): error :   at Mono.Cecil.AssemblyDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters) [0x00000] in <d4dd94f3e5f74095b62543e88f18941d>:0
/Users/ci/buildAgent/work/52fe272bfade4750/packages/Xamarin.Build.Download.0.4.5/build/Xamarin.Build.Download.targets(113,3): error :   at Mono.Cecil.AssemblyDefinition.Write (System.String fileName) [0x00007] in <d4dd94f3e5f74095b62543e88f18941d>:0
/Users/ci/buildAgent/work/52fe272bfade4750/packages/Xamarin.Build.Download.0.4.5/build/Xamarin.Build.Download.targets(113,3): error :   at Xamarin.Build.Download.BaseXamarinBuildResourceRestore.MergeResources (Mono.Cecil.IAssemblyResolver resolver, System.String originalAsmPath, System.String mergedAsmPath, System.String assemblyName, System.Collections.Generic.List`1[T] resourceItems) [0x00117] in <e1d5ce02ef4c499ab3c5d2e5c40caa85>:0
```

When using Sysinternals process explorer, the process holding said file handle hostage came back as MSBuild.exe, so the build process itself.

We have thoroughly gone gone through our .csproj and packages.config files to search for any irregularities, but found none.

My colleague also tried re-ordering some of the package `<Import>` elements in the .csproj file, but the only difference that made is that a different package's DLL file was the subject of the sharing violation. Whichever one is listed first, I believe.

After poking at all sorts of things, this is the one error that kept returning; sometimes it didn't, sometimes it did, almost like a sort of race condition. An earlier attempt to work around it in the XBD package involved inserting delays, and polling to see whether the file was writable yet. At the first attempt, it appeared to be writable after a way of  around 15 seconds, but later I had instances where it would take over 10 minutes.

This result is what tipped me off that it might be an undisposed Stream somewhere, and led me to try running garbage collection manually. Running GC always made the problem go away in one go, no further retries needed. I know manually invoking `GC.Collect()` is frowned upon, but it's letting us carry on with regular work now.

In any case, I decided it'd be good to open this pull request, as you might be able to figure out where the lack of disposing is actually happening. I suspect it might _not_ be in Xamarin.Build.Download, but in Xamarin.Android.Build.Targets someplace.

---

This issue happened both on a Windows build server and an OS X one.

On Windows we are using:

- Xamarin 4.5.0.486 (fec6f88)
- Xamarin.Android 7.3.1.2 (9dbc4c5)
- NuGet 3.5.0.1996
- MSBuild 15.1.1012.6693

The issue also existed on earlier versions of Xamarin.Android SDK, and Xamarin.Build.Download (0.4.3)

Please let me know if you need any further details.

### CODE REVIEW

**Comment by bholmes** [comment]
We are looking into this issue that this PR addresses.  We have not been able to reproduce this problem but will continue to work to do to.  

Also you will find that we are dropping Xamarin Build Download from the build process for Android Support Libraries starting with version 25.4.  

https://nuget.org/packages/Xamarin.Android.Support.Core.Utils/25.4.0-rc1

Upgrading to this version should also avoid the problem.  (Xamairn Build Download is still a dependency of the NuGet, but it is not invoked.  Will be cleaned up in version 26.)

Finally I do have a suggestion to consider if we decide to merge this workaround.  Instead of temporarily opening the stream to test the file lock, I suggest we keep that stream for writing and pass it to `asmDefinition.MainModule.Write (stream, new new WriterParameters ());`.  So attempt to open the stream, if fail collect, then try again and return the stream from one of the attempts.

**Comment by michd** [comment]
Thank you for your response.

I've added a new commit which refactors the workaround a bit, re-using the test `FileStream` as suggested.

Once the Xamarin.Android.Support.X 25.4.0 packages hit stable, we'll update and see if that resolves the problem for us; in all likelihood it will, thank you.

**Comment by newky2k** [comment]
@michd Xamarin.Android.Support is now upto v27.  Can you see if this is still an issue that needs this change to be merged?

**Comment by newky2k** [comment]
@Redth  agreed this is no longer and issue

**Comment by SergeyNesteruk** [comment]
@newky2k Dave, this is still an issue in version 4.12 Preview3 and the Xamarin.GooglePlayServices.Basement.60.1142.0 depends on Xamarin.Build.Download so XBD cannot be omitted.
The proposed pull request fixes the problem. Please reconsider the issue.

**Pull request closed without merging**
