### PR TITLE
TinkAndroid-1.6.1

### PR DESCRIPTION
**Pull request by 4brunu**
This PR is the first step to fix https://github.com/xamarin/AndroidX/issues/346

### CODE REVIEW

**Review by juansturla — APPROVED** [review]
I haven't checked the code in depth, but I have run the cake command successfully, got the nuget, and it worked great inside Xamarin.AndroidX

**Review by juansturla — APPROVED** [review]

**Comment by juansturla** [comment]
Are the empty .xml files necessary?

**Comment by 4brunu** [comment]
Good question, I always created them, so I'm not sure if they are necessary or not.

**Comment by 4brunu** [comment]
@jpobst could you please help to merge this PR and also https://github.com/xamarin/AndroidX/pull/347?
Thanks

**Comment by jpobst** [comment]
Since this is a dependency of AndroidX, we will likely instead implement it in that repo, so it benefits from our automated updating and dependency infrastructure.

**Comment by 4brunu** [comment]
Moved Tink-Android to the repo AndroidX with the PR https://github.com/xamarin/AndroidX/pull/347

**Pull request closed without merging**
