### PR TITLE
[binderator] Include 'runtime' dependencies in dependency tree.

### PR DESCRIPTION
**Pull request by jpobst**
I think this makes sense, but I'm no expert here.

Some `.pom` files list a dependency as scoped to `runtime`:

```
<dependency>
  <groupId>androidx.lifecycle</groupId>
  <artifactId>lifecycle-common</artifactId>
  <version>2.0.0</version>
  <scope>runtime</scope>
</dependency>
```

Today we ignore this dependency and do not add it to the NuGet dependency requirements because we only consider `<scope>compile</scope>`.  However this dependency is needed at runtime and thus users get an error when running their app like:
```
Java.Lang.NoClassDefFoundError: 'Failed resolution of: Landroidx/arch/core/executor/ArchTaskExecutor;
```

It looks like in the past we have manually added these dependencies, but this means an update can break a package if it adds a new runtime dependency: https://github.com/xamarin/AndroidX/blob/master/source/AndroidXProject.cshtml#L164-L185.

### CODE REVIEW

**Comment by mattleibow** [comment]
If this is just runtime, we might want to indicate this in the various types. The thought I have is that we want to include it, but maybe not do a binding or something. Maybe an empty nuget with a targets?

Not sure if we will do that and I suppose we can cross this bridge when we come to it...

**Comment by jpobst** [comment]
That's a good point.  I think we're going to eventually end up having to ship a lot of "jar file in a nuget" packages like `Xamarin.Google.Guava`.  The calls for them are getting louder: https://github.com/xamarin/AndroidX/issues/280.

We'll probably want to extend binderator to do these automatically from `config.json` instead of maintaining them manually.

**Comment by jpobst** [comment]
This was discussed here:
https://discordapp.com/channels/732297728826277939/732297837953679412/833760025821446145

It was decided a better option would probably be to do something like:
- Require each `runtime` dependency to be manually defined in the `config.json`, specifying whether it should be a dependency or not.
- Have `binderator` error out if it encounters any `runtime` dependencies that are not specified, to ensure new dependencies are accounted for.

Maybe something like:
```
{
  "groupId": "androidx.ads",
  "artifactId": "ads-identifier-provider",
  "version": "1.0.0-alpha04",
  "nugetVersion": "1.0.0.5-alpha04",
  "nugetId": "Xamarin.AndroidX.Ads.IdentifierProvider",
  "dependencyOnly": false,
  "includedRuntimeDependencies": ["Xamarin.AndroidX.Blah"],
  "excludedRuntimeDependencies": ["Xamarin.AndroidX.Foo", "Xamarin.AndroidX.Bar"]
}
```

**Comment by jpobst** [comment]
An initial pass at this shows these are the current `runtime` dependencies in AndroidX (89 count):

| Artifact  | Dependency |
| ------------- | ------------- |
androidx.activity.activity|androidx.collection.collection
androidx.activity.activity|androidx.tracing.tracing
androidx.ads.ads-identifier|androidx.ads.ads-identifier-common
androidx.ads.ads-identifier|androidx.concurrent.concurrent-futures
androidx.ads.ads-identifier|androidx.core.core
androidx.ads.ads-identifier|com.google.auto.value.auto-value-annotations
androidx.ads.ads-identifier-provider|androidx.ads.ads-identifier-common
androidx.ads.ads-identifier-provider|androidx.core.core
androidx.ads.ads-identifier-provider|com.google.auto.value.auto-value-annotations
androidx.appcompat.appcompat|androidx.collection.collection
androidx.appcompat.appcompat|androidx.lifecycle.lifecycle-runtime
androidx.appcompat.appcompat|androidx.lifecycle.lifecycle-viewmodel
androidx.appcompat.appcompat-resources|androidx.collection.collection
androidx.autofill.autofill|androidx.core.core
androidx.biometric.biometric|androidx.activity.activity
androidx.biometric.biometric|androidx.appcompat.appcompat
androidx.biometric.biometric|androidx.lifecycle.lifecycle-livedata-core
androidx.biometric.biometric|androidx.lifecycle.lifecycle-viewmodel
androidx.browser.browser|androidx.collection.collection
androidx.browser.browser|androidx.concurrent.concurrent-futures
androidx.browser.browser|androidx.interpolator.interpolator
androidx.camera.camera-camera2|androidx.concurrent.concurrent-futures
androidx.camera.camera-camera2|androidx.core.core
androidx.camera.camera-camera2|com.google.auto.value.auto-value-annotations
androidx.camera.camera-camera2|com.google.guava.listenablefuture
androidx.camera.camera-core|androidx.concurrent.concurrent-futures
androidx.camera.camera-core|androidx.core.core
androidx.camera.camera-core|androidx.exifinterface.exifinterface
androidx.camera.camera-core|androidx.lifecycle.lifecycle-common
androidx.camera.camera-core|com.google.auto.value.auto-value-annotations
androidx.camera.camera-lifecycle|androidx.core.core
androidx.camera.camera-lifecycle|com.google.auto.value.auto-value-annotations
androidx.car.app.app|androidx.activity.activity
androidx.car.app.app|androidx.annotation.annotation
androidx.car.app.app|androidx.annotation.annotation-experimental
androidx.car.app.app|androidx.core.core
androidx.car.app.app|androidx.lifecycle.lifecycle-viewmodel
androidx.core.core|androidx.collection.collection
androidx.core.core-animation|androidx.collection.collection
androidx.core.core-animation|androidx.core.core
androidx.customview.customview|androidx.collection.collection
androidx.emoji.emoji|androidx.collection.collection
androidx.lifecycle.lifecycle-livedata|androidx.arch.core.core-common
androidx.lifecycle.lifecycle-livedata-core|androidx.arch.core.core-common
androidx.lifecycle.lifecycle-livedata-core|androidx.arch.core.core-runtime
androidx.lifecycle.lifecycle-runtime|androidx.arch.core.core-runtime
androidx.media.media|androidx.collection.collection
androidx.media2.media2-common|androidx.collection.collection
androidx.media2.media2-common|androidx.concurrent.concurrent-futures
androidx.media2.media2-session|androidx.collection.collection
androidx.media2.media2-session|androidx.concurrent.concurrent-futures
androidx.media2.media2-widget|androidx.appcompat.appcompat
androidx.media2.media2-widget|androidx.palette.palette
androidx.mediarouter.mediarouter|androidx.appcompat.appcompat
androidx.mediarouter.mediarouter|androidx.palette.palette
androidx.mediarouter.mediarouter|androidx.recyclerview.recyclerview
androidx.navigation.navigation-common|androidx.collection.collection
androidx.navigation.navigation-common|androidx.core.core
androidx.navigation.navigation-common-ktx|androidx.collection.collection
androidx.navigation.navigation-common-ktx|androidx.core.core-ktx
androidx.navigation.navigation-ui|androidx.transition.transition
androidx.paging.paging-runtime|androidx.core.core-ktx
androidx.paging.paging-runtime-ktx|androidx.paging.paging-common-ktx
androidx.paging.paging-rxjava2|org.jetbrains.kotlin.kotlin-stdlib
androidx.paging.paging-rxjava2|org.jetbrains.kotlinx.kotlinx-coroutines-rx2
androidx.paging.paging-rxjava2-ktx|org.jetbrains.kotlin.kotlin-stdlib
androidx.recyclerview.recyclerview|androidx.collection.collection
androidx.recyclerview.recyclerview-selection|androidx.collection.collection
androidx.room.room-guava|androidx.arch.core.core-runtime
androidx.room.room-guava|androidx.concurrent.concurrent-futures
androidx.room.room-runtime|androidx.annotation.annotation-experimental
androidx.room.room-runtime|androidx.arch.core.core-runtime
androidx.room.room-rxjava2|androidx.arch.core.core-runtime
androidx.room.room-rxjava3|androidx.arch.core.core-runtime
androidx.savedstate.savedstate|androidx.arch.core.core-common
androidx.savedstate.savedstate|androidx.lifecycle.lifecycle-common
androidx.security.security-crypto|com.google.crypto.tink.tink-android
androidx.slidingpanelayout.slidingpanelayout|androidx.core.core
androidx.tracing.tracing|androidx.annotation.annotation
androidx.transition.transition|androidx.collection.collection
androidx.window.window|androidx.annotation.annotation
androidx.window.window|androidx.collection.collection
androidx.window.window|androidx.core.core
androidx.window.window-extensions|androidx.annotation.annotation
androidx.work.work-runtime|androidx.core.core
androidx.work.work-runtime|androidx.lifecycle.lifecycle-service
androidx.work.work-runtime|androidx.room.room-runtime
androidx.work.work-runtime|androidx.sqlite.sqlite
androidx.work.work-runtime|androidx.sqlite.sqlite-framework

A few of these we take care of manually in the `csproj` [template](https://github.com/xamarin/AndroidX/blob/main/source/AndroidXProject.cshtml#L191-L220).  

The rest are unaccounted for.

I guess the question is:
- Is missing these a problem?

Most of these look pretty common, and I suspect they just happen to get filled by other AndroidX packages the user has referenced.

Here's the only listed dependencies that we do not currently reference in AndroidX:

- com.google.auto.value.auto-value-annotations:1.6.3
- org.jetbrains.kotlinx.kotlinx-coroutines-rx2:1.4.3
- com.google.crypto.tink.tink-android:1.5.0

We have bindings for `auto-value-annotations` and `kotlinx-coroutines-rx2`.  `tink-android` is the only one we are missing.

**Comment by jpobst** [comment]
Replaced with https://github.com/xamarin/XamarinComponents/pull/1230.

**Pull request closed without merging**
