### PR TITLE
OkHttp3 and OkHttp3UrlConnection 4.9.3

### PR DESCRIPTION
**Pull request by 4brunu**
Bump OkHttp3 and OkHttp3UrlConnection bind to 4.9.3

### CODE REVIEW

**Review by moljac — APPROVED** [review]
LGTM

**Comment by tranb3r** [comment]
@moljac This PR was prepared two months ago. What is blocking the release ?

**Comment by moljac** [comment]
> @moljac This PR was prepared two months ago. What is blocking the release ?

build was red and I didn't dive in deeper.

Let me restart builds.

**Comment by tranb3r** [comment]
@moljac Why does it take so long ? Is it blocked again ?

**Comment by tranb3r** [comment]
Come on guys ! What's going on ?

**Comment by moljac** [comment]
> Come on guys ! What's going on ?

Maybe tons to do? Could be problems?

**Comment by tranb3r** [comment]
How can we help ?

**Comment by moljac** [comment]
> How can we help ?

I wish you could. It is google's mess I am trying to solve. Now there is besides `guava:3x.y-android`, also `gauva:3x.y-jre` dependency. And suffix means it is preview, but no it is not, so it breaks every single deterministic algorithm. My task is simply to add exclusions/exceptions to rules.

**Comment by moljac** [comment]
@tranb3r I need to publish several guava packages from XC (this) repo, so I'll try to publish other PRs.

**Comment by 4brunu** [comment]
This PR got splitted into https://github.com/xamarin/XamarinComponents/pull/1337 and https://github.com/xamarin/XamarinComponents/pull/1338 for OkHttp and OkHttpUrlConnection 4.9.3 respectively.

**Pull request closed without merging**
