### PR TITLE
Coil-1.4.0

### PR DESCRIPTION
**Pull request by 4brunu**
Update Coil and CoilBase to 1.4.0

### CODE REVIEW

**Review by moljac — APPROVED** [review]
LGTM

**Comment by moljac** [comment]
@4brunu 

needs newer dependency:

```
         /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(131,5): error : Unable to find package Xamarin.Io.CoilKt.CoilBase with version (>= 1.4.0) [/Users/runner/work/1/s/Android/Coil/source/Coil.sln]
       /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(131,5): error :   - Found 1 version(s) in nuget.org [ Nearest version: 1.3.2 ] [/Users/runner/work/1/s/Android/Coil/source/Coil.sln]
```

**Comment by 4brunu** [comment]
@moljac this PR updates both Coil and CoilBase to 1.4.0.
Coil depends on CoilBase, and since they are both in this PR the build will fail.
What do you prefer, a PR with both Coil and CoilBase or a PR for each?

**Comment by moljac** [comment]
maybe 2 (if possible) 

I think I need 2 tags for those (not sure 100%)

**Comment by 4brunu** [comment]
Ok, I will create two PRs 👍

**Comment by 4brunu** [comment]
This PR was splitted into https://github.com/xamarin/XamarinComponents/pull/1335 and https://github.com/xamarin/XamarinComponents/pull/1336, for CoilBase 1.4.0 and Coil 1.4.0 respectively.

**Pull request closed without merging**
