### PR TITLE
Updated SceneForm to 1.10.0

### PR DESCRIPTION
**Pull request by craigktreasure**
This PR is a follow-up to #629 that updates the SceneForm bindings to version 1.10.0 consuming ARCore 1.10.0 and updates the hellosceneform sample app to run successfully.

I did all of this from Windows with VS 2019 16.2 and ran into a few issues. I don't know if the experience is better on a Mac, but I'll document my processes, workarounds, and pain points here for feedback and future reference.

## My process

After I updated the source files for SceneForm 1.10.0 and ARCore 1.10.0, i restored the externals by running `..\..\build.ps1 -Targets externals` from `Android\SceneForm`.

Upon opening `SceneForm.sln` in Visual Studio 2019 16.2, I was presented with warnings about `NuGet.Frameworks.FrameworkException: Invalid framework identifier`. The value for `TargetFrameworks` is `MonoAndroid81`. I think this is a side effect of using the `MSBuild.Sdk.Extras` package to enable the awesome new SDK project style. I worked around this by closing the solution, manually restoring packages for the solution from the console (`nuget restore ./SceneForm.sln`), and then re-opening the solution.

While attempting to build the solution, I encountered errors in the `UX` project in a few files with `no suitable method found to override`.

I gave up trying to build it from within Visual Studio and just built it from the console since there seems to be a suitable `cake.build` for this project. I ran `..\..\build.ps1 -Target nuget`, which produced all of the NuGet packages without a problem.

I put the newly minted SceneForm NuGet packages into a local folder configured in my NuGet.config file as a local feed. I then opened `HelloSceneform.sln` in Visual Studio and unloaded the SceneForm projects, since they won't build in VS for me. Then, I configured the hellosceneform project to use the 1.10.0-preview1 version of the `Xamarin.Android.SceneForm.UX` NuGet package, which I previously built and put in a local NuGet feed folder with all its dependencies, instead of all the project references.

I was then able to deploy the hellosceneform app using ARCore and SceneForm 1.10.0 to my Pixel 3.

While running the hellosceneform sample app, I immediately encountered a crash with a "Material version mismatch. Expected 3 but received 1" error that occurred when trying to load the `andy.sfb` asset. I had to produce an updated Andy asset using Android Studio.

My process for updating `andy.sfb`:

1. Cloned the https://github.com/google-ar/sceneform-android-sdk/ repository and checked out the `v1.10.0` tag (ok, the tag they created is a bit funky, so I used the commit hash for that tag).
2. Replaced `samples/hellosceneform/app/sampledata/models/andy.png` in the _sceneform-android-sdk_ repository with `Android/ARCore/samples/HelloAR/Assets/andy.png` from the _XamarinComponents_ repository.
3. Built the `samples/hellosceneform` project in Android Studio to produce a new `andy.sfb` at `samples/hellosceneform/app/src/main/res/raw/andy.sfb`.
4. Replaced `Android/SceneForm/samples/HelloSceneForm/Resources/raw/andy.sfb` in the _XamarinComponents_ repository with the updated `andy.sfb` from the _sceneform-android-sdk_ repository.

After that, i was able to rebuild, deploy, and run the Xamarin hellosceneform sample app using ARCore and SceneForm 1.10.0 successfully with a great looking Xamarin Andy (Xandy?). Success!

### CODE REVIEW

**Comment by Redth** [comment]
Thanks for the detailed info!

I made a few changes to the PR which seem to make the experience in VS2019 a bit better when loading the .sln.

The one thing I'm seeing locally and also in CI is the sample having errors with the `AnimationEngine$AnimationEngineListener` type.  It seems like the generator is creating an issue in the Android callable wrapper.  I'm looking into this currently.

I'm kind of surprised you aren't seeing the same:

```
obj/Release/android/src/mono/com/google/ar/sceneform/animation/AnimationEngine_AnimationEngineListenerImplementor.java:8: error: cannot find symbol
  		com.google.ar.sceneform.animation.AnimationEngine.AnimationEngineListener
  		                                                 ^
    symbol:   class AnimationEngineListener
    location: class AnimationEngine
```

**Comment by craigktreasure** [comment]
I'm seeing the same after pulling your changes when running `..\..\build.ps1 -Target samples`. I wonder if I didn't see it before because of how I worked around the issues with building the SceneForm projects in VS.

**Comment by craigktreasure** [comment]
Things do appear to behave a bit better is VS 2019, however, i'm still unable to build the UX project due to `no suitable method found to override` errors:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0115	'RotationController.OnEndTransformation(Object)': no suitable method found to override	UX	C:\Users\crtreasu\Repos\XamarinComponents_craig\Android\SceneForm\source\UX\RotationController.cs	12	Active
Error	CS0115	'RotationController.OnContinueTransformation(Object)': no suitable method found to override	UX	C:\Users\crtreasu\Repos\XamarinComponents_craig\Android\SceneForm\source\UX\RotationController.cs	26	Active
Error	CS0115	'RotationController.CanStartTransformation(Object)': no suitable method found to override	UX	C:\Users\crtreasu\Repos\XamarinComponents_craig\Android\SceneForm\source\UX\RotationController.cs	40	Active
Error	CS0115	'ScaleController.OnEndTransformation(Object)': no suitable method found to override	UX	C:\Users\crtreasu\Repos\XamarinComponents_craig\Android\SceneForm\source\UX\ScaleController.cs	13	Active
Error	CS0115	'ScaleController.OnContinueTransformation(Object)': no suitable method found to override	UX	C:\Users\crtreasu\Repos\XamarinComponents_craig\Android\SceneForm\source\UX\ScaleController.cs	27	Active
Error	CS0115	'ScaleController.CanStartTransformation(Object)': no suitable method found to override	UX	C:\Users\crtreasu\Repos\XamarinComponents_craig\Android\SceneForm\source\UX\ScaleController.cs	41	Active
Error	CS0115	'TranslationController.OnEndTransformation(Object)': no suitable method found to override	UX	C:\Users\crtreasu\Repos\XamarinComponents_craig\Android\SceneForm\source\UX\TranslationController.cs	10	Active
Error	CS0115	'TranslationController.OnContinueTransformation(Object)': no suitable method found to override	UX	C:\Users\crtreasu\Repos\XamarinComponents_craig\Android\SceneForm\source\UX\TranslationController.cs	24	Active
Error	CS0115	'TranslationController.CanStartTransformation(Object)': no suitable method found to override	UX	C:\Users\crtreasu\Repos\XamarinComponents_craig\Android\SceneForm\source\UX\TranslationController.cs	38	Active
```

Are you not seeing the same?

**Comment by Redth** [comment]
I did originally see those but after doing a delete of bin/obj those went away and I'm just left with the java compilation failure which we're looking at.

**Comment by craigktreasure** [comment]
Ah, I see. I'm now able to repro the same thing from VS 2019.

**Comment by Redth** [comment]
Ack! Ok tl;dr: Google did something funny with `AnimationEngine.AnimationEngineListener` and we're going to exclude it from the binding at least for now.

Basically it _seems_ like they used `$` in the actual java source code name of the `AnimationEngine$AnimationEngineListener` interface and our generator can't cope with that (this is a very unorthodox thing to do in java).

**Comment by craigktreasure** [comment]
That's odd. I was able to build and run it just fine by building the NuGet packages and configuring the sample project to use those packages. For my understanding in the way I ran it previously, when would this become a problem? At runtime when you try to use `AnimationEngine.AnimationEngineListener`?

**Comment by Redth** [comment]
I'm not sure how that ever built properly for you... Maybe an older xamarin.android version somehow let it slide? Really not sure... When the java callable wrapper is generated when you build the app project, it generates incorrectly and should never work.

**Comment by Redth** [comment]
@craigktreasure if we can live without that interface for now, this PR is good to go.

**Pull request merged**
