### PR TITLE
kotlin-1.5.20

### PR DESCRIPTION
**Pull request by 4brunu**
bump kotlin to 1.5.20

### CODE REVIEW

**Review by moljac — APPROVED** [review]

**Comment by 4brunu** [comment]
@moljac any news on merging and publish this PR?
That would be nice because it would unlock the update of kotlinx coroutines in https://github.com/xamarin/XamarinComponents/pull/1234 that depends on this PR.
Thanks 👍

**Comment by moljac** [comment]
@4brunu 

I messed up a bit... I merged 1.5.21 before 1.5.20, so be careful in the future, for future bumps!!

**Comment by 4brunu** [comment]
Should I close this PR?

**Comment by moljac** [comment]
@4brunu No. It is OK.

Just in main there will be 1.5.20 instead of 1.5.21... FYI warning only

**Comment by 4brunu** [comment]
Ok Ok, thanks for letting me know 👍

**Pull request merged**
