### PR TITLE
AudioSwitch-1.1.4

### PR DESCRIPTION
**Pull request by 4brunu**
AudioSwitch 1.1.3 added support to Android 12, because of the bluetooth changes, but also introduced some bugs.
AudioSwitch 1.1.4 fixes those bugs.

### CODE REVIEW

**Review by moljac — APPROVED** [review]
LGTM

**Comment by 4brunu** [comment]
@moljac it's weird that this fails to build em macOS, I have tested this locally and it builds successfully.
Could you please check what is the error in the build output please? Because I don't have access to it.

**Comment by moljac** [comment]
> @moljac it's weird that this fails to build em macOS, I have tested this locally and it builds successfully. Could you please check what is the error in the build output please? Because I don't have access to it.

Here:

```
     2>/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Legacy.targets(267,5): error XA0000: Could not determine API level for $(TargetFrameworkVersion) of 'v12.0'. [/Users/runner/work/1/s/Android/AudioSwitch/source/AudioSwitch/AudioSwitch.csproj]
     2>Done Building Project "/Users/runner/work/1/s/Android/AudioSwitch/source/AudioSwitch/AudioSwitch.csproj" (Build target(s)) -- FAILED.
     2>Done Building Project "/Users/runner/work/1/s/Android/AudioSwitch/source/AudioSwitch/AudioSwitch.csproj" (Pack target(s)) -- FAILED.
     1>Done Building Project "/Users/runner/work/1/s/Android/AudioSwitch/source/AudioSwitch.sln" (Pack target(s)) -- FAILED.

```

**Comment by 4brunu** [comment]
Thanks, CI is now passing 👍

**Pull request merged**
