### PR TITLE
Update SwiftRuntimeSupport to a version from 2021

### LINKED ISSUE #13605: Unable to bind native iOS framework that uses Async/Await in iOS 13
### Steps to Reproduce

1. In the sample project open SwiftAsyncAwaitExample.sln
2. run SwiftAsyncAwaitExample in iOS 13 or iOS 14.
3. check the console for the Native Crash Reporting.

```
=================================================================
	Native Crash Reporting
=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x1048ea2a5 - /Users/user/Library/Developer/CoreSimulator/Devices/B9B09834-5F56-4157-84F2-7693D7B75FE7/data/Containers/Bundle/Application/0DA75164-3DCC-4120-8178-FF577ECDE608/SwiftAsyncAwaitExample.app/SwiftAsyncAwaitExample : mono_dump_native_crash_info
	0x1048de6ee - /Users/user/Library/Developer/CoreSimulator/Devices/B9B09834-5F56-4157-84F2-7693D7B75FE7/data/Containers/Bundle/Application/0DA75164-3DCC-4120-8178-FF577ECDE608/SwiftAsyncAwaitExample.app/SwiftAsyncAwaitExample : mono_handle_native_crash
	0x1048f15f9 - /Users/user/Library/Developer/CoreSimulator/Devices/B9B09834-5F56-4157-84F2-7693D7B75FE7/data/Containers/Bundle/Application/0DA75164-3DCC-4120-8178-FF577ECDE608/SwiftAsyncAwaitExample.app/SwiftAsyncAwaitExample : mono_sigsegv_signal_handler_debug
	0x7fff51421e2d - /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 13.0.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x6000030b68c0 - Unknown
	0x7fff50b7029b - /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 13.0.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCore.dylib : _ZN5swift8Demangle9Demangler16demangleOperatorEv
	0x7fff50b6eaa8 - /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 13.0.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCore.dylib : _ZN5swift8Demangle9Demangler12demangleTypeEN4llvm9StringRefE
	0x7fff50b5c375 - /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 13.0.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCore.dylib : _ZL30swift_getTypeByMangledNameImplN5swift15MetadataRequestEN4llvm9StringRefEPKPKvNSt3__18functionIFPKNS_14TargetMetadataINS_9InProcessEEEjjEEENS8_IFPKNS_18TargetWitnessTableISA_EESD_jEEE
	0x7fff50b5a0e2 - /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 13.0.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCore.dylib : _ZN5swift26swift_getTypeByMangledNameENS_15MetadataRequestEN4llvm9StringRefEPKPKvNSt3__18functionIFPKNS_14TargetMetadataINS_9InProcessEEEjjEEENS8_IFPKNS_18TargetWitnessTableISA_EESD_jEEE
	0x7fff50b5a1d9 - /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 13.0.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCore.dylib : swift_getTypeByMangledNameInContext
	0x10529f157 - /Users/user/Library/Developer/CoreSimulator/Devices/B9B09834-5F56-4157-84F2-7693D7B75FE7/data/Containers/Bundle/Application/0DA75164-3DCC-4120-8178-FF577ECDE608/SwiftAsyncAwaitExample.app/Frameworks/SwiftAsyncAwaitFramework.framework/SwiftAsyncAwa : __swift_instantiateConcreteTypeFromMangledName
	0x10529f59c - /Users/user/Library/Developer/CoreSimulator/Devices/B9B09834-5F56-4157-84F2-7693D7B75FE7/data/Containers/Bundle/Application/0DA75164-3DCC-4120-8178-FF577ECDE608/SwiftAsyncAwaitExample.app/Frameworks/SwiftAsyncAwaitFramework.framework/SwiftAsyncAwa : __swift_instantiateConcreteTypeFromMangledName
	0x104b3b599 - /Users/user/Library/Developer/CoreSimulator/Devices/B9B09834-5F56-4157-84F2-7693D7B75FE7/data/Containers/Bundle/Application/0DA75164-3DCC-4120-8178-FF577ECDE608/SwiftAsyncAwaitExample.app/SwiftAsyncAwaitExample : xamarin_dyn_objc_msgSend
	0x10aded290 - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7fff50b57e37):0x7fff50b57e27  0f 40 84 f6 74 0a 48 8b 3b be ed 00 00 00 eb 21  .@..t.H.;......!
0x7fff50b57e37  8b 02 89 c1 80 e1 1f 80 f9 03 74 0b 80 f9 04 75  ..........t....u
0x7fff50b57e47  1f 66 b8 ef 00 eb 04 66 b8 85 00 48 8b 3b 0f b7  .f.....f...H.;..
0x7fff50b57e57  f0 48 83 c4 08 5b 41 5e 41 5f 5d e9 d9 71 01 00  .H...[A^A_]..q..

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at ApiDefinitions.Messaging:void_objc_msgSend_IntPtr <0x000ef>
	  at SwiftAsyncAwaitFramework.SwiftAsyncAwait:FunctionThatCallsPrivateAsyncFunctionWithClosure <0x0028a>
	  at SwiftAsyncAwaitExample.AppDelegate:FinishedLaunching <0x001d2>
	  at <Module>:runtime_invoke_bool__this___object_object <0x00205>
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x00254>
	  at UIKit.UIApplication:Main <0x00172>
	  at SwiftAsyncAwaitExample.Application:Main <0x00092>
	  at <Module>:runtime_invoke_void_object <0x00198>
=================================================================
```

### Expected Behavior

With the release of Xcode 13.2, Async/Await is now backwards compatible and works on iOS 13 and above.
So Async/Await is expected to work on iOS 13 and above.

### Actual Behavior

Xamarin.iOS throws a Native Crash Reporting when calling a method of a native iOS framework that uses async/await on iOS 13.

### Environment

```
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.10.16 (build 2)
Installation UUID: 95a87c0e-b7a0-472f-8ea5-7c2fba2958ae
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/5.0.404/Sdks
SDK Versions:
	5.0.404
	3.1.416
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.13
	3.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.416

=== .NET 5.0 SDK ===

SDK: 5.0.404

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 12.0.0.3 (Visual Studio Enterprise)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Applications/android-sdk
	Supported Android versions:
		5.1 (API level 22)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 31.0.0

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

=== Eclipse Temurin JDK ===

Java SDK: Not Found

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

=== Xamarin Designer ===

Version: 16.11.0.39
Hash: cd672761d
Branch: remotes/origin/d16-11
Build date: 2021-10-06 21:09:18 UTC

=== Apple Developer Tools ===

Xcode 13.2.1 (19586)
Build 13C100

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 15.4.0.0 (Visual Studio Enterprise)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Build Information ===

Release ID: 810160002
Git revision: 6dbc7886fa608147f685a7df3912249400c84716
Build date: 2021-12-14 15:54:37-05
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.1.0
Darwin 21.2.0 Darwin Kernel Version 21.2.0
    Sun Nov 28 20:28:54 PST 2021
    root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
```

### Build Logs

https://gist.github.com/4brunu/55e4c18a9b8455cb492c01a84026ccdc

### Example Project (If Possible)

The directory SwiftAsyncAwaitFramework contains a native iOS Framework that uses Async/Await on iOS 13 and above, and also a native sample app SwiftAsyncAwaitAppExample, to test the Async/Await on iOS 13 and above, and it works.

The directory SwiftAsyncAwaitBinding contains the xamarin binding of the native iOS library.

The directory SwiftAsyncAwaitExample contains a Xamarin app to test the xamarin binding of the native iOS library.

[SwiftAsyncAwaitExample.zip](https://github.com/xamarin/xamarin-macios/files/7741846/SwiftAsyncAwaitExample.zip)

### PR DESCRIPTION
**Pull request by chamons**
- Fixes https://github.com/xamarin/xamarin-macios/issues/13605

All of the cake builds fail for me locally due to [this](https://gist.github.com/chamons/d189b15f2e11111404124864d92ebf59) so I created a package manually with these steps reverse engineered from the cake file:

```
msbuild /t:Build /p:Configuration=Release  SwiftRuntimeSupport.sln
msbuild /t:Pack /p:Configuration=Release /p:PackageOutputPath=/Users/donblas/Programming/XamarinComponents/iOS/SwiftRuntimeSupport/output/ /p:PackageRequireLicenseAcceptance=true /p:IncludeBuildOutput=false
```

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]

**Comment by dalexsoto** [comment]
@SotoiGhost can you have a look? this should enable Swift async support

**Comment by SotoiGhost** [comment]
@chamons In case you need it, we are using an old version of Cake. Run `dotnet tool install Cake.Tool --version 0.33.0` to make it work.

**Review by SotoiGhost — APPROVED** [review]

**Comment by EmmanVazz** [comment]
When will this be fixed? It is currently blocking some of us like shown here https://developercommunity.visualstudio.com/t/Xamarin-iOS-codesign-failed-with-exit-co/1631600?space=8&entry=problem&q=codesign+failed&sort=newest&page=8

**Comment by quentinR0bert** [comment]
Hi, it's seem we have an anomaly since this version : https://github.com/xamarin/XamarinComponents/issues/1358

**Pull request merged**
