### PR TITLE
ARCore - fix Trackable is not a Plane, and other issues

### LINKED ISSUE #1305: trackable is not a Plane
https://github.com/xamarin/XamarinComponents/blob/3c4cffd0409b53444279c345eac31c291ec4115c/Android/ARCore/samples/HelloAR/MainActivity.cs#L258

I tried to deploy the sample, but no anchors are created because of trackable variable isn't an instance of Plane, even if using the debugger I see that it's com.google.ar.core.Plane.

Why?
@moljac

### PR DESCRIPTION
**Pull request by nCastle1**
I wasn't able to find contribution guidelines or any sign of CLA requirements. Please let me know if I've missed something.

Summary: attempts to resolve https://github.com/xamarin/XamarinComponents/issues/1305

Background: with the changes to update to ARCore 1.24.0, the binding implementation was simplified. Unfortunately, the simplified binding code resulted in several types (`Plane`, `Point`) not implementing `ITrackable`, which breaks a lot of hit testing/anchoring scenarios.

Caution: This is my first time looking at Xamarin Android bindings, and I don't really understand how they work. This is a humble request for someone with binding expertise to take a look at this PR.

Testing: I created a nuget package locally and tested it with a custom app. Visual Studio is showing the pre-1.24.0 API (`Plane` extends `TrackableBase` which implements `ITrackable`). Hit testing works and cursory testing shows basic AR scenarios are running as expected. I haven't tested anything involving faces, depth, or instant placement.

Additional notes:

- NuGet version is bumped to ~1.26.0.1. There are newer versions of ARCore available, but the release notes suggest scary changes between 26 and 29. I'd think it wise to release a fixed version of 26 (or perhaps go all the way back to 24), and then publish releases for each of the intervening ARCore versions, to ensure users have choice. Does Xamarin have guidelines/polices for keeping package versions in sync with third-party libraries?~ 1.29.0
- I set the assembly version value. Visual Studio shows it in some cases. It is weird when everything is always version 1.0.0. Happy to revert that if there's a reason this wasn't already done.
- ~Metadata.xml content was mostly from reverting an older commit, and then making changes following a pattern. I didn't make formatting changes, for ease of review. I'd be happy to clean up the formatting if that's desired.~ PR has since been simplified; major change is restoring an entry to Metadata.xml for TrackableBase.

### CODE REVIEW

**Comment by softlion** [comment]
I can't see any TrackableBase  in your code changes ?
What is the exact issue with the generated code and how do you think you solved it ?

Also unfortunately upgrading to the latest version of the arcore lib is mandatory, even with "scary changes", as those changes are implemented in a dynamically loaded and updated apk from google play on every user devices. So not upgrading the lib may result in non working app anyway.

Also you reactivated the Downloads.Client and other obsolete features. That's not a good idea :)

**Comment by nCastle1** [comment]
My original approach was to return to the previously-known-to-work solution, and extend if for new API. If you look at Xamarin.Google.ARCore.dll with ildasm.exe, you'll see that `TrackableBase` doesn't exist in the current released version, but is restored in the package built with this PR. You can also look at e.g. Plane in Visual Studio and see that it is defined as a plain `Java.Lang.Object` rather than a trackable in the released package:

<details><summary>First 80 lines of Plane (as decompiled by Visual Studio) before change</summary><p>

```cs
#region Assembly Xamarin.Google.ARCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// location unknown
// Decompiled with ICSharpCode.Decompiler 6.1.0.5902
#endregion

using Android.Runtime;
using Java.Interop;
using Java.Lang;
using Java.Nio;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;

namespace Google.AR.Core
{
    [Register("com/google/ar/core/Plane", DoNotGenerateAcw = true)]
    public class Plane : Java.Lang.Object
    {
        [Register("com/google/ar/core/Plane$Type", DoNotGenerateAcw = true)]
        public sealed class Type : Java.Lang.Enum
        {
            private static readonly JniPeerMembers _members = new XAPeerMembers("com/google/ar/core/Plane$Type", typeof(Type));

            [Register("HORIZONTAL_DOWNWARD_FACING")]
            public static Type HorizontalDownwardFacing => Java.Lang.Object.GetObject<Type>(_members.StaticFields.GetObjectValue("HORIZONTAL_DOWNWARD_FACING.Lcom/google/ar/core/Plane$Type;").Handle, JniHandleOwnership.TransferLocalRef);

            [Register("HORIZONTAL_UPWARD_FACING")]
            public static Type HorizontalUpwardFacing => Java.Lang.Object.GetObject<Type>(_members.StaticFields.GetObjectValue("HORIZONTAL_UPWARD_FACING.Lcom/google/ar/core/Plane$Type;").Handle, JniHandleOwnership.TransferLocalRef);

            [Register("VERTICAL")]
            public static Type Vertical => Java.Lang.Object.GetObject<Type>(_members.StaticFields.GetObjectValue("VERTICAL.Lcom/google/ar/core/Plane$Type;").Handle, JniHandleOwnership.TransferLocalRef);

            internal static IntPtr class_ref => _members.JniPeerType.PeerReference.Handle;

            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            [EditorBrowsable(EditorBrowsableState.Never)]
            public override JniPeerMembers JniPeerMembers => _members;

            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            [EditorBrowsable(EditorBrowsableState.Never)]
            protected override IntPtr ThresholdClass => _members.JniPeerType.PeerReference.Handle;

            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            [EditorBrowsable(EditorBrowsableState.Never)]
            protected override System.Type ThresholdType => _members.ManagedPeerType;

            internal Type(IntPtr javaReference, JniHandleOwnership transfer)
                : base(javaReference, transfer)
            {
            }

            [Register("valueOf", "(Ljava/lang/String;)Lcom/google/ar/core/Plane$Type;", "")]
            public unsafe static Type ValueOf(string name)
            {
                IntPtr intPtr = JNIEnv.NewString(name);
                try
                {
                    JniArgumentValue* ptr = stackalloc JniArgumentValue[1];
                    *ptr = new JniArgumentValue(intPtr);
                    return Java.Lang.Object.GetObject<Type>(_members.StaticMethods.InvokeObjectMethod("valueOf.(Ljava/lang/String;)Lcom/google/ar/core/Plane$Type;", ptr).Handle, JniHandleOwnership.TransferLocalRef);
                }
                finally
                {
                    JNIEnv.DeleteLocalRef(intPtr);
                }
            }

            [Register("values", "()[Lcom/google/ar/core/Plane$Type;", "")]
            public static Type[] Values()
            {
                return (Type[])JNIEnv.GetArray(_members.StaticMethods.InvokeObjectMethod("values.()[Lcom/google/ar/core/Plane$Type;", null).Handle, JniHandleOwnership.TransferLocalRef, typeof(Type));
            }
        }

        private static readonly JniPeerMembers _members = new XAPeerMembers("com/google/ar/core/Plane", typeof(Plane));

        private static Delegate cb_getAnchors;

        private static Delegate cb_getCenterPose;
```

</p></details>

<details><summary>First 80 lines of Plane after change</summary><p>

```cs
#region Assembly Xamarin.Google.ARCore, Version=1.26.0.1, Culture=neutral, PublicKeyToken=null
// location unknown
// Decompiled with ICSharpCode.Decompiler 6.1.0.5902
#endregion

using Android.Runtime;
using Java.Interop;
using Java.Lang;
using Java.Nio;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;

namespace Google.AR.Core
{
    [Register("com/google/ar/core/Plane", DoNotGenerateAcw = true)]
    public class Plane : TrackableBase
    {
        [Register("com/google/ar/core/Plane$Type", DoNotGenerateAcw = true)]
        public sealed class Type : Java.Lang.Enum
        {
            private static readonly JniPeerMembers _members = new XAPeerMembers("com/google/ar/core/Plane$Type", typeof(Type));

            [Register("HORIZONTAL_DOWNWARD_FACING")]
            public static Type HorizontalDownwardFacing => Java.Lang.Object.GetObject<Type>(_members.StaticFields.GetObjectValue("HORIZONTAL_DOWNWARD_FACING.Lcom/google/ar/core/Plane$Type;").Handle, JniHandleOwnership.TransferLocalRef);

            [Register("HORIZONTAL_UPWARD_FACING")]
            public static Type HorizontalUpwardFacing => Java.Lang.Object.GetObject<Type>(_members.StaticFields.GetObjectValue("HORIZONTAL_UPWARD_FACING.Lcom/google/ar/core/Plane$Type;").Handle, JniHandleOwnership.TransferLocalRef);

            [Register("VERTICAL")]
            public static Type Vertical => Java.Lang.Object.GetObject<Type>(_members.StaticFields.GetObjectValue("VERTICAL.Lcom/google/ar/core/Plane$Type;").Handle, JniHandleOwnership.TransferLocalRef);

            internal static IntPtr class_ref => _members.JniPeerType.PeerReference.Handle;

            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            [EditorBrowsable(EditorBrowsableState.Never)]
            public override JniPeerMembers JniPeerMembers => _members;

            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            [EditorBrowsable(EditorBrowsableState.Never)]
            protected override IntPtr ThresholdClass => _members.JniPeerType.PeerReference.Handle;

            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            [EditorBrowsable(EditorBrowsableState.Never)]
            protected override System.Type ThresholdType => _members.ManagedPeerType;

            internal Type(IntPtr javaReference, JniHandleOwnership transfer)
                : base(javaReference, transfer)
            {
            }

            [Register("valueOf", "(Ljava/lang/String;)Lcom/google/ar/core/Plane$Type;", "")]
            public unsafe static Type ValueOf(string name)
            {
                IntPtr intPtr = JNIEnv.NewString(name);
                try
                {
                    JniArgumentValue* ptr = stackalloc JniArgumentValue[1];
                    *ptr = new JniArgumentValue(intPtr);
                    return Java.Lang.Object.GetObject<Type>(_members.StaticMethods.InvokeObjectMethod("valueOf.(Ljava/lang/String;)Lcom/google/ar/core/Plane$Type;", ptr).Handle, JniHandleOwnership.TransferLocalRef);
                }
                finally
                {
                    JNIEnv.DeleteLocalRef(intPtr);
                }
            }

            [Register("values", "()[Lcom/google/ar/core/Plane$Type;", "")]
            public static Type[] Values()
            {
                return (Type[])JNIEnv.GetArray(_members.StaticMethods.InvokeObjectMethod("values.()[Lcom/google/ar/core/Plane$Type;", null).Handle, JniHandleOwnership.TransferLocalRef, typeof(Type));
            }
        }

        private static Delegate cb_getAnchors;

        private static IntPtr id_getAnchors;

        private static readonly JniPeerMembers _members = new XAPeerMembers("com/google/ar/core/Plane", typeof(Plane));
```

</p></details>

re: downloads.client, it doesn't seem the changes made any difference to the compiled output. The exposed API is the same regardless. I'll remove it since it isn't useful. I assume there isn't a reason it was commented out, rather than just deleted.

I've taken another look at the original PR that broke trackables, and it looks like the primary issue is that `TrackableBase` was commented out in addition to the `com.google.ar.core.services.downloads` package names. The output DLL looks correct if I uncomment out the **Metadata.xml** entry for `TrackableBase` but otherwise restore **Metadata.xml** and **Additions.cs** to their original state. Assuming that testing shows everything is working, I'll update this PR to reflect this feedback, to be followed with an update to the latest ARCore version.

**Comment by softlion** [comment]
Instead of TrackableBase, is ITrackable enough ? It's already public. And the android doc confirms that's the intention:

image

So something like this should be enough (also remove the remove in metadata then):

```
namespace Google.AR.Core
{
    // Add ITrackable interface
    public partial class Plane : Google.AR.Core.ITrackable {}
}
```

Also i can't find com.google.ar.core.services.downloads.aidl in the doc and think those classes are not used anymore. Where do you see their usage ?

**Comment by nCastle1** [comment]
I don't see any uses of com.google.ar.core.services.downloads.aidl, you were right to remove it.

I looked at the changes in #1318 and confirmed they solve the problem this PR was made to solve. I'm going to close this PR and wait for #1318 to be merged.

**Pull request closed without merging**
