### PR TITLE
Add nh firebase dependency

### PR DESCRIPTION
**Pull request by marstr**
Waded through the dependency tree, made the change necessary to have a minimum set of dependencies needed to run this application. After this, all a person should have to do is register their app with Firebase, download the `google-services.json` and add it to the Properties portion of their application and set the Build action to 'GoogleServicesJson'.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/xamarin/XamarinComponents?pullRequest=907) <br/>All CLA requirements met.

**Comment by marstr** [comment]
I guess one notable change, is that the build process now directly targets the Project, instead of creating a Local Nuget, and having the build phase publish there.

Now that I understand better what is happening, I could work on altering it back to that. Personally I think it's a bit of unnecessary complication, but I'll yield to other folk's opinions on this. The big pro of altering this back would be that it more closely resembles an outside project's acquisition path.

**Review by mattleibow — APPROVED** [review]

**Comment by mattleibow** [comment]
In most cases, we just use project references. This project might have used NuGets for some reason - maybe @Redth will have an idea. But, I think this is just nicer for general dev.

**Comment by marstr** [comment]
Nice, I'm happy with this then. Once this is merged, we can release an updated version of the NuGet as well (the existing one doesn't work.) Maybe call it `v1.0.0-preview2.1`?

**Comment by mattleibow** [comment]
@marstr we can do that!

When updating the packages, just update the version number in the build.cake file. That is used when creating the package. I did that for now, and when CI is all green, I'll release.

Thanks for this!

**Comment by mattleibow** [comment]
@marstr it is LIVE!!! 

https://www.nuget.org/packages/Xamarin.Azure.NotificationHubs.Android/1.0.0-preview2.1

**Comment by marstr** [comment]
Thanks @mattleibow!

**Pull request merged**
