### PR TITLE
OkHttp3-4.9.2

### PR DESCRIPTION
**Pull request by 4brunu**
bump OkHttp bind to 4.9.2

### CODE REVIEW

**Comment by tranb3r** [comment]
What is going on ? Why are all PR checks in error ?

**Comment by 4brunu** [comment]
I don't know, because locally they are passing

**Comment by tranb3r** [comment]
@moljac Do you know what is going on ? Thank you !

**Comment by tranb3r** [comment]
@jpobst Could you please take a look ? Thank you.

**Comment by moljac** [comment]
@tranb3r @4brunu 

.NET 6 RC version was removed from CDN (downloads), so I updated it. Also created PR 

https://github.com/xamarin/XamarinComponents/pull/1287

**Comment by 4brunu** [comment]
Do I need to do any changes to this PR?
Thanks

**Comment by moljac** [comment]
> Do I need to do any changes to this PR? Thanks

Nope. Looking good. Thanks for your help.

**Comment by moljac** [comment]
@tranb3r @4brunu

Note: some (if not all) OKHttp (actually `Square.*`) will move to GPS-FB-MLKit (stuff higher on maintenance priority ladder).

**Comment by 4brunu** [comment]
Nice, thanks for letting me know

**Review by moljac — APPROVED** [review]
LGTM

**Comment by tranb3r** [comment]
@moljac @4brunu 
Is there something more to do in order to trigger the nuget release?

**Pull request merged**
