### PR TITLE
Update MaterialComponents to the latest version(92.0.0)

### PR DESCRIPTION
**Pull request by newky2k**

### CODE REVIEW

**Comment by mattleibow** [comment]
Should this be merged first? https://github.com/xamarin/XamarinComponents/pull/666

**Comment by Digifais** [comment]
@newky2k Could we have another bump to v92.4.0 before this gets possibly merged?

**Comment by dkornev** [comment]
Hi @newky2k,

First of all thanks for maintaining the MaterialComponents bindings for Xamarin.
Why this pull request hasn't been merged yet? Do you need any help with it?

**Comment by Digifais** [comment]
@mattleibow Could you shine some light on this PR? The material components for iOS got updated to v94.2.0 in the meanwhile.

**Comment by AyonAB** [comment]
Why this haven't marged yet?

**Review by Redth — APPROVED** [review]

**Comment by MarvinFrankenfeld** [comment]
I am not able to use the actionsheetcontroller with the latest version 92.0.0-rc2. I get the following error:

dyld: Symbol not found: _OBJC_CLASS_$_MDCActionSheetAction
  Referenced from: /var/containers/Bundle/Application/566E3562-7714-44EE-AAB2-D4EF4A487B95/UInterface.iOS.app/UInterface.iOS
  Expected in: /private/var/containers/Bundle/Application/566E3562-7714-44EE-AAB2-D4EF4A487B95/UInterface.iOS.app/Frameworks/MaterialComponents.framework/MaterialComponents
 in /var/containers/Bundle/Application/566E3562-7714-44EE-AAB2-D4EF4A487B95/UInterface.iOS.app/UInterface.iOS

**Comment by ChasakisD** [comment]
@newky2k Same issue here. ActionSheetController Class pointer is zero

**Comment by gadeweever** [comment]
@ChasakisD or @MarvinFrankenfeld Did you find a solution for this? Our application is terminating on launch with: 

dyld: Symbol not found: _OBJC_CLASS_$_MDCActionSheetAction
  Referenced from: /var/containers/Bundle/Application/0D9D1D8F-CC3E-4825-ACF9-1342A9C90E28/APP.UX.iOS.app/APP.UX.iOS
  Expected in: /private/var/containers/Bundle/Application/0D9D1D8F-CC3E-4825-ACF9-1342A9C90E28/APP.UX.iOS.app/Frameworks/MaterialComponents.framework/MaterialComponents
 in /var/containers/Bundle/Application/0D9D1D8F-CC3E-4825-ACF9-1342A9C90E28/APP.UX.iOS.app/APP.UX.iOS

**Comment by ChasakisD** [comment]
@gadeweever Use latest stable version. It's fixed there!

**Comment by gadeweever** [comment]
@ChasakisD Thanks! For some reason it reproe'd until I cleaned the project and rebuilt. Thinks sheem okay now.

**Pull request merged**
