### PR TITLE
[Crashlytics] Bindings done.

### PR DESCRIPTION
**Pull request by adlair**

### CODE REVIEW

**Comment by jldubz** [comment]
Is there an ETA for when this will be approved?  There are less than 3 weeks remaining until current crash analytics will be turned off, and I would appreciate some time to test implementing the new libraries before then.

**Comment by gerardmrk** [comment]
Also requesting for an ETA. We're currently needing to install a crash-reporter and would prefer using Crashlytics over other solutions out there. 

If we know the approximate date this gets published, we can decide if it's worth waiting for it or whether to just use another alternative like Microsoft's App Center.

Appreciate any info. Please note I am not trying to push for a faster release, I'm just requesting for an estimated date this will be completed by, so we can make an informed decision. Thanks!

**Comment by whithajess** [comment]
The feature branch looks to be in the PR stage now: https://github.com/xamarin/XamarinComponents/pull/441

**Comment by Redth** [comment]
Yes we are reviewing the PR and should have something released this week. I've done some basic testing and am able to get crashes showing up in firebase console.

**Comment by whithajess** [comment]
Awesome - thanks @Redth

**Comment by gerardmrk** [comment]
Thanks @Redth

**Pull request merged**
