### PR TITLE
update Kotlin libs to 1.3.61

### PR DESCRIPTION
**Pull request by antonioseric**
Update to latest Kotlin libs https://mvnrepository.com/artifact/org.jetbrains.kotlin/

### CODE REVIEW

**Comment by 4brunu** [comment]
Any news on this?
[Kotlin 1.3.70](https://github.com/JetBrains/kotlin/releases/tag/v1.3.70) just got released today and I would like to upgrade. 🙂

**Review by mattleibow — APPROVED** [review]

**Comment by mattleibow** [comment]
@antonioseric Thanks for the PR. Looks good.

**Comment by antonioser** [comment]
@mattleibow do you know when will nuget be available on nuget.org? 

@4brunu I started looking into 1.3.70

**Comment by 4brunu** [comment]
@antonioser could you please instead integrate 1.3.71? Thanks

**Comment by antonioseric** [comment]
@mattleibow Can we release this nuget package?

**Comment by mattleibow** [comment]
Updated to use the new binding tools and released.

**Pull request merged**
