### PR TITLE
Binderator dependency version null fix

### PR DESCRIPTION
**Pull request by moljac**
Fix for handling dependencies without version specified.

binderator could not handle dependencies without version like in `com.google.protobuf:protobuf-lite` POM.xml file

https://repo1.maven.org/maven2/com/google/protobuf/protobuf-lite/3.0.1/protobuf-lite-3.0.1.pom

Following snippet caused NRE:

```xml
<dependencies>
<dependency>
<groupId>junit</groupId>
<artifactId>junit</artifactId>
</dependency>
<dependency>
<groupId>org.easymock</groupId>
<artifactId>easymock</artifactId>
</dependency>
<dependency>
<groupId>org.easymock</groupId>
<artifactId>easymockclassextension</artifactId>
</dependency>
</dependencies>
```

Details:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
<modelVersion>4.0.0</modelVersion>
<parent>
<groupId>com.google.protobuf</groupId>
<artifactId>protobuf-parent</artifactId>
<version>3.0.0</version>
</parent>
<version>3.0.1</version>
<artifactId>protobuf-lite</artifactId>
<packaging>bundle</packaging>
<name>Protocol Buffers [Lite]</name>
<description>A trimmed-down version of the Protocol Buffers library.</description>
<dependencies>
<dependency>
<groupId>junit</groupId>
<artifactId>junit</artifactId>
</dependency>
<dependency>
<groupId>org.easymock</groupId>
<artifactId>easymock</artifactId>
</dependency>
<dependency>
<groupId>org.easymock</groupId>
<artifactId>easymockclassextension</artifactId>
</dependency>
</dependencies>
<properties>
<core.root>../core</core.root>
<test.proto.dir>${core.root}/src/test/proto</test.proto.dir>
<protoc-gen-javalite>${protobuf.source.dir}/protoc-gen-javalite</protoc-gen-javalite>
</properties>
<build>
<sourceDirectory>${core.root}/src/main/java</sourceDirectory>
<testSourceDirectory>${core.root}/src/test/java</testSourceDirectory>
<plugins>
<!--  Use Antrun plugin to generate sources with protoc  -->
<plugin>
<artifactId>maven-antrun-plugin</artifactId>
<executions>
<!--  Generate core protos  -->
<execution>
<id>generate-sources</id>
<phase>generate-sources</phase>
<configuration>
<target>
<ant antfile="generate-sources-build.xml"/>
</target>
</configuration>
<goals>
<goal>run</goal>
</goals>
</execution>
<!--  Generate the test protos  -->
<execution>
<id>generate-test-sources</id>
<phase>generate-test-sources</phase>
<configuration>
<target>
<ant antfile="generate-test-sources-build.xml"/>
</target>
</configuration>
<goals>
<goal>run</goal>
</goals>
</execution>
</executions>
</plugin>
<!--  Only compile a subset of the files  -->
<plugin>
<artifactId>maven-compiler-plugin</artifactId>
<configuration>
<generatedSourcesDirectory>${generated.sources.lite.dir}</generatedSourcesDirectory>
<generatedTestSourcesDirectory>${generated.testsources.lite.dir}</generatedTestSourcesDirectory>
<includes>
<include>**/AbstractMessageLite.java</include>
<include>**/AbstractParser.java</include>
<include>**/AbstractProtobufList.java</include>
<include>**/BooleanArrayList.java</include>
<include>**/ByteString.java</include>
<include>**/CodedInputStream.java</include>
<include>**/CodedOutputStream.java</include>
<include>**/DoubleArrayList.java</include>
<include>**/ExtensionLite.java</include>
<include>**/ExtensionRegistryLite.java</include>
<include>**/FieldSet.java</include>
<include>**/FloatArrayList.java</include>
<include>**/GeneratedMessageLite.java</include>
<include>**/IntArrayList.java</include>
<include>**/Internal.java</include>
<include>**/InvalidProtocolBufferException.java</include>
<include>**/LazyFieldLite.java</include>
<include>**/LazyStringArrayList.java</include>
<include>**/LazyStringList.java</include>
<include>**/LongArrayList.java</include>
<include>**/MapEntryLite.java</include>
<include>**/MapFieldLite.java</include>
<include>**/MessageLite.java</include>
<include>**/MessageLiteOrBuilder.java</include>
<include>**/MessageLiteToString.java</include>
<include>**/MutabilityOracle.java</include>
<include>**/NioByteString.java</include>
<include>**/Parser.java</include>
<include>**/ProtobufArrayList.java</include>
<include>**/ProtocolStringList.java</include>
<include>**/RopeByteString.java</include>
<include>**/SmallSortedMap.java</include>
<include>**/TextFormatEscaper.java</include>
<include>**/UninitializedMessageException.java</include>
<include>**/UnknownFieldSetLite.java</include>
<include>**/UnmodifiableLazyStringList.java</include>
<include>**/UnsafeByteOperations.java</include>
<include>**/Utf8.java</include>
<include>**/WireFormat.java</include>
</includes>
<testIncludes>
<testInclude>**/*Lite.java</testInclude>
<testInclude>**/BooleanArrayListTest.java</testInclude>
<testInclude>**/DoubleArrayListTest.java</testInclude>
<testInclude>**/FloatArrayListTest.java</testInclude>
<testInclude>**/IntArrayListTest.java</testInclude>
<testInclude>**/LazyMessageLiteTest.java</testInclude>
<testInclude>**/LiteTest.java</testInclude>
<testInclude>**/LongArrayListTest.java</testInclude>
<testInclude>**/NioByteStringTest.java</testInclude>
<testInclude>**/ProtobufArrayListTest.java</testInclude>
<testInclude>**/UnknownFieldSetLiteTest.java</testInclude>
</testIncludes>
</configuration>
</plugin>
<!--  OSGI bundle configuration  -->
<plugin>
<groupId>org.apache.felix</groupId>
<artifactId>maven-bundle-plugin</artifactId>
<extensions>true</extensions>
<configuration>
<instructions>
<Bundle-DocURL>https://developers.google.com/protocol-buffers/</Bundle-DocURL>
<Bundle-SymbolicName>com.google.protobuf</Bundle-SymbolicName>
<Export-Package>com.google.${project.artifactId};version=${project.version}</Export-Package>
</instructions>
</configuration>
</plugin>
</plugins>
</build>
</project>
```

### CODE REVIEW

**Comment by jpobst** [comment]
It looks like this fix ignores dependencies without versions, which probably works in this case because these look like unit testing assemblies.  But I wonder if that's always a valid assumption we can make.  What if a future library has a required dependency without a version number?  We would never know about it and would ship broken packages.

Maybe a better fix for now is to extend the `excludedRuntimeDependencies` logic to apply to all dependencies instead of just runtime dependencies:

https://github.com/xamarin/XamarinComponents/blob/main/Util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Engine.cs#L446-L448

This would force us to check each dependency without a version and explicitly exclude it at the artifact level, so none get missed.

**Comment by jpobst** [comment]
Ugh, it looks like the "proper" way to handle this in POM is to look at the `<parent>` element:
```xml
<parent>
  <groupId>com.google.protobuf</groupId>
  <artifactId>protobuf-parent</artifactId>
  <version>3.0.0</version>
</parent>
```

Then you have to go get this parent POM to get the versions:
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-parent/3.0.0/protobuf-parent-3.0.0.pom

```xml
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.easymock</groupId>
      <artifactId>easymock</artifactId>
      <version>2.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.easymock</groupId>
      <artifactId>easymockclassextension</artifactId>
      <version>2.2.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>18.0</version>
    </dependency>
  </dependencies>
</dependencyManagement>
```

We are also able to retrieve a `<scope>` from these dependencies and see that they are all `test`, so we don't need them.

From: https://stackoverflow.com/a/63714398

Ideally we would probably implement this feature, but it may be too much effort to be worth it, and we just need to manually manage a few dependencies manually.  I'm not sure how many of our libraries rely on "parent" POMs.

**Comment by moljac** [comment]
> What if a future library has a required dependency without a version number? We would never know about it and would ship broken packages.

I think it is impossible to have dependency without a version.

https://stackoverflow.com/questions/29476472/maven-dependency-without-version

what I did in my utilities (which wait for me to finish this migration) - I created classes based on XSD and that should cover most of the cases we have:

https://maven.apache.org/xsd/maven-4.0.0.xsd


> We are also able to retrieve a <scope> from these dependencies and see that they are all test, so we don't need them.

For now I will try today if it works:
- exclusion list
- scope ignore rule (`<scope>test</scope>`)

> but it may be too much effort to be worth it, and we just need to manually manage a few dependencies manually. 

My problem is time right now. I hope exclusion list will work.

> I'm not sure how many of our libraries rely on "parent" POMs.

not sure, it is new feature and I expect number[s] to grow.

**Comment by jpobst** [comment]
Does this actually fix it?  Per your original POM, there is not a `<scope>test</scope>` specified:
```
<dependencies>
  <dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
  </dependency>
  <dependency>
    <groupId>org.easymock</groupId>
    <artifactId>easymock</artifactId>
  </dependency>
  <dependency>
    <groupId>org.easymock</groupId>
    <artifactId>easymockclassextension</artifactId>
  </dependency>
</dependencies>
```

You can only find out they are `test` if you implement the stuff to pull `<dependencyManagement>` information from the parent POM.

So I think `binderator` will still include these dependencies without versions.

**Comment by moljac** [comment]
> Does this actually fix it? 

Both solutions did prevent runtime crash in binderator (MavenNET), but logic was wrong for dependencies.

> You can only find out they are `test` if you implement the stuff to pull `<dependencyManagement>` information from the parent POM.

Grabbing parent POM must be done in MavenNET which needs several fixes I have on my list. 
 
> So I think `binderator` will still include these dependencies without versions.

I need to do more tests, but both versions did not include these dependencies. Here is sample with following test

```csharp
			// TODO: MavenNET - implement the stuff to pull version from <dependencyManagement> information
			//	 from the parent POM.
			if (string.IsNullOrEmpty(dependency.Version))
				return false;
```

resulting in:

```xml
<Project Sdk="Xamarin.Legacy.Sdk">
  <PropertyGroup>
    <TargetFrameworks>MonoAndroid9.0;net6.0-android</TargetFrameworks>
    <IsBindingProject>true</IsBindingProject>
    <!--
      No warnings for:
       - CS0618: 'member' is obsolete: 'text'
       - CS0109: The member 'member' does not hide an inherited member. The new keyword is not required
       - CS0114: 'function1' hides inherited member 'function2'. To make the current method override that implementation, add the override keyword. Otherwise add the new keyword.
       - CS0628: 'member' : new protected member declared in sealed class
       - CS0108: 'member1' hides inherited member 'member2'. Use the new keyword if hiding was intended.
       - CS0809: Obsolete member 'member' overrides non-obsolete member 'member'
    -->
    <NoWarn>0618;0109;0114;0628;0108;0809</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <AndroidClassParser>class-parse</AndroidClassParser>
    <AndroidCodegenTarget>XAJavaInterop1</AndroidCodegenTarget>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Microsoft</Authors>
    <Owners>Microsoft</Owners>
    <Copyright>© Microsoft Corporation. All rights reserved.</Copyright>
    <PackageLicenseUrl>https://go.microsoft.com/fwlink/?linkid=865435</PackageLicenseUrl>
    <PackageProjectUrl>https://go.microsoft.com/fwlink/?linkid=865435</PackageProjectUrl>
    <PackageLicenseUrl>https://go.microsoft.com/fwlink/?linkid=865373</PackageLicenseUrl>
    <RepositoryUrl>https://github.com/google/protobuf</RepositoryUrl>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>

      <PackageId>Xamarin.Protobuf.Lite</PackageId>
      <RootNamespace>Xamarin.Protobuf.Lite</RootNamespace>
      <AssemblyName>Xamarin.Protobuf.Lite</AssemblyName>
            <Title>Xamarin.Protobuf.Lite</Title>
            <PackageDescription>
                Bindings for Google's Protobuf Lite package (Google Play Services dependency)
            </PackageDescription>
            <PackageTags>xamarin, android, bindings, google, protobuf, lite</PackageTags>
      <PackageVersion>3.0.1</PackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <TransformFile Include="..\..\source\com.google.protobuf\protobuf-lite\Transforms\*.xml" Link="Transforms\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\source\com.google.protobuf\protobuf-lite\Additions\*.cs" Link="Additions\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <LibraryProjectZip 
        Include="..\..\externals\com.google.protobuf\protobuf-lite.aar" Link="Jars\%(Filename)%(Extension)" 
        Condition="Exists('..\..\externals\com.google.protobuf\protobuf-lite.aar')"
         />
    <Embeddedjar 
        Include="..\..\externals\com.google.protobuf\protobuf-lite.jar" Link="Jars\%(Filename)%(Extension)" 
        Condition="Exists('..\..\externals\com.google.protobuf\protobuf-lite.jar')"
        />
    <JavaSourcesJar Include="..\..\externals\com.google.protobuf\protobuf-lite-sources.jar" Link="Jars\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\templates\protobuf-lite\LICENSE.md" Pack="true" PackagePath="LICENSE.md" />
    <None Include="..\..\templates\protobuf-lite\External-Dependency-Info.txt" Pack="true" PackagePath="THIRD-PARTY-NOTICES.txt" />
  </ItemGroup>

</Project>
```

So, dependencies were not added. Which is OK for workaround, because downloading artifact will be impossible without version.

The only problem was that there is dependency on `com.google.guava:guava:18.0` without a scope 

```xml
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.12</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.easymock</groupId>
        <artifactId>easymock</artifactId>
        <version>2.2</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.easymock</groupId>
        <artifactId>easymockclassextension</artifactId>
        <version>2.2.1</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>18.0</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

And it can be added manually in Razor template what we do in other cases:

https://github.com/xamarin/GooglePlayServicesComponents/blob/main/source/GooglePlayServicesProject.cshtml#L261-L284

```
  <ItemGroup>
    <!-- PackageReference -->
    @foreach (var dep in @Model.NuGetDependencies) {
      if (!dep.IsProjectReference) {
      <PackageReference Include="@(dep.NuGetPackageId)" Version="@(dep.NuGetVersion)" PrivateAssets="none" />
      }
    }
    @if (@Model.NuGetPackageId == "Xamarin.GooglePlayServices.SafetyNet")
    {
      <Reference Include="System.Net.Http" />
      <PackageReference Include="System.Text.Json" Version="5.0.2" />
    }
    @if (@Model.NuGetPackageId == "Xamarin.Firebase.Firestore")
    {
      <PackageReference Include="Xamarin.Google.Guava" Version="28.2.0.1" />
    }
    @if (@Model.NuGetPackageId == "Xamarin.Firebase.Crashlytics")
    {
      <PackageReference Include="Xamarin.Google.Dagger" Version="2.27.0" />
    }

    <!-- Reference -->
    <Reference Include="System.Net.Http" Condition=" '$(TargetFramework)' == '@(targetFrameworkMoniker)' " />
  </ItemGroup>
```

Making the workaround like this:

```
      <PackageReference Include="Xamarin.Google.Guava" Version="29.0.0" />
```

https://github.com/xamarin/GooglePlayServicesComponents/blob/template-sets-protobuf/templates/protobuf-lite/Project.cshtml#L51

**Comment by jpobst** [comment]
I think the `if (string.IsNullOrEmpty(dependency.Version))` mechanism goes back to my original concern: if any dependencies are added in the future which use parent dependencies we will never know about them and potentially produce bad packages.

I definitely understand not spending the effort right now to properly implement parent dependencies. I think we can fix this as a hack for now in a way that won't cause us to silently produce bad packages by extending the `excludedRuntimeDependencies` to apply to any type of dependency.

This is accomplished by moving the `// Check 'artifact' list` and `// Check 'global' list` checks to the top of `ShouldIncludeDependency (...)`.  Then we can add the 3 `test` assemblies to the `excludedRuntimeDependencies` section of the `protobuf:protobuf-lite` entry in `config.json`.

I don't think we will actually need to add a reference to `com.google.guava.guava`.  My understanding of the parent dependencies is that it lists all possible dependencies, but if the child `protobuf-lite-3.0.1.pom` doesn't list it, the package does not use it.

**Comment by moljac** [comment]
> I think the `if (string.IsNullOrEmpty(dependency.Version))` mechanism goes back to my original concern: if any dependencies are added in the future which use parent dependencies we will never know about them and potentially produce bad packages.

Isn't the logic that the package is excluded (skipped) if `ShouldIncludeDependency (...)` returns `false`? So, package without a version will not be added, which might be problem, but it can be added manually in the Razor template.

Even if we add some dependency (nuget package) I think "bad package" is a bit harsh, because it will just be unused `PackageReference`. Or am I wrong?

> I definitely understand not spending the effort right now to properly implement parent dependencies. I think we can fix this as a hack for now in a way that won't cause us to silently produce bad packages by extending the `excludedRuntimeDependencies` to apply to any type of dependency.

I tried that and result was the same. Packages were not added. OK with `excludedRuntimeDependencies` we have control over outcome.

> This is accomplished by moving the `// Check 'artifact' list` and `// Check 'global' list` checks to the top of `ShouldIncludeDependency (...)`. Then we can add the 3 `test` assemblies to the `excludedRuntimeDependencies` section of the `protobuf:protobuf-lite` entry in `config.json`.

I am doing semantical analysis (trying to grasp/understand) and I think I'll get the same result, i.e. packages will be excluded.

I don't think moving code will be necessary, but let me try it locally again.

Only part that returns `true` (including a package) is:

```csharp
			// We always care about 'compile' scoped dependencies
			if (dependency.IsCompileDependency())
				return true;
```

all other cases exclude dependency, so moving `// Check 'artifact' list` and `// Check 'global' list` might not be necessary.

https://github.com/xamarin/XamarinComponents/blob/binderator-dependency-version-null-fix/Util/Xamarin.AndroidBinderator/Xamarin.AndroidBinderator/Engine.cs#L439-L441

> 
> I don't think we will actually need to add a reference to `com.google.guava.guava`. My understanding of the parent dependencies is that it lists all possible dependencies, but if the child `protobuf-lite-3.0.1.pom` doesn't list it, the package does not use it.

This is the part where I lost most of the time last week - understanding packages w/o `scope` or what defaults for omitted `scope`. I thought `compile` or `runtime` and proposed to add `guava`.

**Comment by moljac** [comment]
with 

```csharp
			// TODO: MavenNET - implement the stuff to pull version from <dependencyManagement> information
			//	 from the parent POM.
			if (string.IsNullOrEmpty(dependency.Version))
				return false;
```

csproj:

```xml
<Project Sdk="Xamarin.Legacy.Sdk">
  <PropertyGroup>
    <TargetFrameworks>MonoAndroid9.0;net6.0-android</TargetFrameworks>
    <IsBindingProject>true</IsBindingProject>
    <!--
      No warnings for:
       - CS0618: 'member' is obsolete: 'text'
       - CS0109: The member 'member' does not hide an inherited member. The new keyword is not required
       - CS0114: 'function1' hides inherited member 'function2'. To make the current method override that implementation, add the override keyword. Otherwise add the new keyword.
       - CS0628: 'member' : new protected member declared in sealed class
       - CS0108: 'member1' hides inherited member 'member2'. Use the new keyword if hiding was intended.
       - CS0809: Obsolete member 'member' overrides non-obsolete member 'member'
    -->
    <NoWarn>0618;0109;0114;0628;0108;0809</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <AndroidClassParser>class-parse</AndroidClassParser>
    <AndroidCodegenTarget>XAJavaInterop1</AndroidCodegenTarget>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Microsoft</Authors>
    <Owners>Microsoft</Owners>
    <Copyright>© Microsoft Corporation. All rights reserved.</Copyright>
    <PackageLicenseUrl>https://go.microsoft.com/fwlink/?linkid=865435</PackageLicenseUrl>
    <PackageProjectUrl>https://go.microsoft.com/fwlink/?linkid=865435</PackageProjectUrl>
    <PackageLicenseUrl>https://go.microsoft.com/fwlink/?linkid=865373</PackageLicenseUrl>
    <RepositoryUrl>https://github.com/google/protobuf</RepositoryUrl>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>

      <PackageId>Xamarin.Protobuf.Lite</PackageId>
      <RootNamespace>Xamarin.Protobuf.Lite</RootNamespace>
      <AssemblyName>Xamarin.Protobuf.Lite</AssemblyName>
            <Title>Xamarin.Protobuf.Lite</Title>
            <PackageDescription>
                Bindings for Google's Protobuf Lite package (Google Play Services dependency)
            </PackageDescription>
            <PackageTags>xamarin, android, bindings, google, protobuf, lite</PackageTags>
      <PackageVersion>3.0.1</PackageVersion>
      <PackageReference Include="Xamarin.Google.Guava" Version="29.0.0" />
  </PropertyGroup>

  <ItemGroup>
    <TransformFile Include="..\..\source\com.google.protobuf\protobuf-lite\Transforms\*.xml" Link="Transforms\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\source\com.google.protobuf\protobuf-lite\Additions\*.cs" Link="Additions\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <LibraryProjectZip 
        Include="..\..\externals\com.google.protobuf\protobuf-lite.aar" Link="Jars\%(Filename)%(Extension)" 
        Condition="Exists('..\..\externals\com.google.protobuf\protobuf-lite.aar')"
         />
    <Embeddedjar 
        Include="..\..\externals\com.google.protobuf\protobuf-lite.jar" Link="Jars\%(Filename)%(Extension)" 
        Condition="Exists('..\..\externals\com.google.protobuf\protobuf-lite.jar')"
        />
    <JavaSourcesJar Include="..\..\externals\com.google.protobuf\protobuf-lite-sources.jar" Link="Jars\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\templates\protobuf-lite\LICENSE.md" Pack="true" PackagePath="LICENSE.md" />
    <None Include="..\..\templates\protobuf-lite\External-Dependency-Info.txt" Pack="true" PackagePath="THIRD-PARTY-NOTICES.txt" />
  </ItemGroup>

</Project>
```

without `IsNullOrEmpty` check no project and solution generation, because of missing dependencies:

```
Dependency errors : 3
1
        System.Exception: 
No matching artifact config found for: 
                        junit.junit:
to satisfy dependency of: 
                        com.google.protobuf.protobuf-lite:3.0.1

        Please add following json snippet to config.json:


      {
        "groupId": "junit",
        "artifactId": "junit",
        "version": "",
        "nugetVersion": "CHECK PREFIX ",
        "nugetId": "CHECK NUGET ID",
        "dependencyOnly": true/false
      }



2
        System.Exception: 
No matching artifact config found for: 
                        org.easymock.easymock:
to satisfy dependency of: 
                        com.google.protobuf.protobuf-lite:3.0.1

        Please add following json snippet to config.json:


      {
        "groupId": "org.easymock",
        "artifactId": "easymock",
        "version": "",
        "nugetVersion": "CHECK PREFIX ",
        "nugetId": "CHECK NUGET ID",
        "dependencyOnly": true/false
      }



3
        System.Exception: 
No matching artifact config found for: 
                        org.easymock.easymockclassextension:
to satisfy dependency of: 
                        com.google.protobuf.protobuf-lite:3.0.1

        Please add following json snippet to config.json:


      {
        "groupId": "org.easymock",
        "artifactId": "easymockclassextension",
        "version": "",
        "nugetVersion": "CHECK PREFIX ",
        "nugetId": "CHECK NUGET ID",
        "dependencyOnly": true/false
      }
```

with `// Check 'artifact' list` and `// Check 'global' list` moved to the front and:

```json
      {
        "groupId": "com.google.protobuf",
        "artifactId": "protobuf-lite",
        "version": "3.0.1",
        "nugetVersion": "3.0.1",
        "nugetId": "Xamarin.Protobuf.Lite",
        "dependencyOnly": false,
        "templateSet": "protobuf-lite",
        "excludedRuntimeDependencies": "junit.junit,org.easymock.easymock,org.easymock.easymockclassextension,com.google.truth.truth"
      },
      {
        "groupId": "com.google.protobuf",
        "artifactId": "protobuf-javalite",
        "version": "3.14.0",
        "nugetVersion": "3.14.0",
        "nugetId": "Xamarin.Protobuf.JavaLite",
        "dependencyOnly": false,
        "templateSet": "protobuf-lite",
        "excludedRuntimeDependencies": "junit.junit,org.easymock.easymock,org.easymock.easymockclassextension,com.google.truth.truth"
      },
```

csproj:

```xml
<Project Sdk="Xamarin.Legacy.Sdk">
  <PropertyGroup>
    <TargetFrameworks>MonoAndroid9.0;net6.0-android</TargetFrameworks>
    <IsBindingProject>true</IsBindingProject>
    <!--
      No warnings for:
       - CS0618: 'member' is obsolete: 'text'
       - CS0109: The member 'member' does not hide an inherited member. The new keyword is not required
       - CS0114: 'function1' hides inherited member 'function2'. To make the current method override that implementation, add the override keyword. Otherwise add the new keyword.
       - CS0628: 'member' : new protected member declared in sealed class
       - CS0108: 'member1' hides inherited member 'member2'. Use the new keyword if hiding was intended.
       - CS0809: Obsolete member 'member' overrides non-obsolete member 'member'
    -->
    <NoWarn>0618;0109;0114;0628;0108;0809</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <AndroidClassParser>class-parse</AndroidClassParser>
    <AndroidCodegenTarget>XAJavaInterop1</AndroidCodegenTarget>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Microsoft</Authors>
    <Owners>Microsoft</Owners>
    <Copyright>© Microsoft Corporation. All rights reserved.</Copyright>
    <PackageLicenseUrl>https://go.microsoft.com/fwlink/?linkid=865435</PackageLicenseUrl>
    <PackageProjectUrl>https://go.microsoft.com/fwlink/?linkid=865435</PackageProjectUrl>
    <PackageLicenseUrl>https://go.microsoft.com/fwlink/?linkid=865373</PackageLicenseUrl>
    <RepositoryUrl>https://github.com/google/protobuf</RepositoryUrl>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>

      <PackageId>Xamarin.Protobuf.Lite</PackageId>
      <RootNamespace>Xamarin.Protobuf.Lite</RootNamespace>
      <AssemblyName>Xamarin.Protobuf.Lite</AssemblyName>
            <Title>Xamarin.Protobuf.Lite</Title>
            <PackageDescription>
                Bindings for Google's Protobuf Lite package (Google Play Services dependency)
            </PackageDescription>
            <PackageTags>xamarin, android, bindings, google, protobuf, lite</PackageTags>
      <PackageVersion>3.0.1</PackageVersion>
      <PackageReference Include="Xamarin.Google.Guava" Version="29.0.0" />
  </PropertyGroup>

  <ItemGroup>
    <TransformFile Include="..\..\source\com.google.protobuf\protobuf-lite\Transforms\*.xml" Link="Transforms\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\source\com.google.protobuf\protobuf-lite\Additions\*.cs" Link="Additions\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <LibraryProjectZip 
        Include="..\..\externals\com.google.protobuf\protobuf-lite.aar" Link="Jars\%(Filename)%(Extension)" 
        Condition="Exists('..\..\externals\com.google.protobuf\protobuf-lite.aar')"
         />
    <Embeddedjar 
        Include="..\..\externals\com.google.protobuf\protobuf-lite.jar" Link="Jars\%(Filename)%(Extension)" 
        Condition="Exists('..\..\externals\com.google.protobuf\protobuf-lite.jar')"
        />
    <JavaSourcesJar Include="..\..\externals\com.google.protobuf\protobuf-lite-sources.jar" Link="Jars\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\templates\protobuf-lite\LICENSE.md" Pack="true" PackagePath="LICENSE.md" />
    <None Include="..\..\templates\protobuf-lite\External-Dependency-Info.txt" Pack="true" PackagePath="THIRD-PARTY-NOTICES.txt" />
  </ItemGroup>

</Project>
```

**Comment by jpobst** [comment]
> Isn't the logic that the package is excluded (skipped) if ShouldIncludeDependency (...) returns false? So, package without a version will not be added, which might be problem, but it can be added manually in the Razor template.

> Even if we add some dependency (nuget package) I think "bad package" is a bit harsh, because it will just be unused PackageReference. Or am I wrong?

This is all correct.  Having an extra `<PackageReference>` isn't much of an issue.

My concern is more about detecting this issue in the future.

Let's say after we bind this, `protobuf-lite 4.0` comes out next month.  It adds a new required dependency of `kotlin-stdlib 1.5.31` by specifying it in the parent POM:
```
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib</artifactId>
      <version>1.5.31</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
```

And then adds the needed dependency to the `protobuf-lite 4.0` POM:
```
<dependencies>
  <dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-stdlib</artifactId>
  </dependency>
</dependencies>
```

If we are simply ignoring any dependency that does not have a version number, our tooling will ignore this new required dependency and create a NuGet package that does not specify Kotlin as a dependency, which will be broken for users.

We can fix this by adding the `<PackageReference>` manually, however I doubt we would know to add it because the tooling isn't notifying us about it.  When we do updates, we don't manually check every updated package's POM to see if new dependencies have been added (and we don't want to).

By forcing us to specify the ignored packages in `excludedRuntimeDependencies` it means that when this situation comes up in the future our tooling will error with something like: `Unknown dependency 'kotlin-stdlib' version <blank>`.  We will then know to investigate this new dependency so we can take the appropriate action (ignore it in `excludedRuntimeDependencies` or add it as a manual `<PackageReference>`).

**Review by jpobst — APPROVED** [review]

**Pull request merged**
