### PR TITLE
refreshed CI settings

### PR DESCRIPTION
**Pull request by moljac**
- bumped several nuget versions
- matching builds for Xamarin.Android

### CODE REVIEW

**Review by jonathanpeppers — COMMENTED** [review]
Does this also need to update the `android` workload?

https://github.com/xamarin/XamarinComponents/blob/df29e1fe1db5a744f3f1336e8a888b87ecfbb159/azure-pipelines.yml#L80-L83

**Comment by moljac** [comment]
> Does this also need to update the `android` workload?
> 
> https://github.com/xamarin/XamarinComponents/blob/df29e1fe1db5a744f3f1336e8a888b87ecfbb159/azure-pipelines.yml#L80-L83

Not sure. But I think it makes sense to update.

**Comment by moljac** [comment]
Added snippet for workload installation and update from AX and/or GPS-FB-MLKit

**Review by jonathanpeppers — COMMENTED** [review]
Like we did in AndroidX / GPS, can we "spot check" some of the `.nupkg` files to make sure the file sizes are the same?

**Comment by moljac** [comment]
> Like we did in AndroidX / GPS, can we "spot check" some of the `.nupkg` files to make sure the file sizes are the same?

this would be quite difficult for XC repo. it builds according to manifest only folder involved in the PR. So if TensorFlow was updated it would build only TensorFlow.

Maybe closing this PR w/o merging?

**Comment by jonathanpeppers** [comment]
@moljac can you make a small change in Tensorflow to test at least one of them?

**Comment by moljac** [comment]
> @moljac can you make a small change in Tensorflow to test at least one of them?

OK
I will bind the same version as in GPS-FB-MLKit, so that we have one parameter less to take into account.

Should I multitarget `net6.0`? 

We left it here as `monoandroid9.0`

https://github.com/xamarin/XamarinComponents/blob/main/XPlat/TensorFlow.Lite/source/Xamarin.TensorFlow.Lite.Bindings.XamarinAndroid/Xamarin.TensorFlow.Lite.Bindings.XamarinAndroid.csproj#L12

**Comment by jonathanpeppers** [comment]
@moljac can you pick one that targets .NET 6? Maybe Xamarin.Android.Glide?

**Review by jonathanpeppers — APPROVED** [review]
This one looks fine now, but does https://github.com/xamarin/XamarinComponents/pull/1398 replace it? It seems like that one also updates the Android workload.

**Comment by jpobst** [comment]
One thing to keep in mind when changing `.yaml` files for this repository is that it is set up to always use the YAML from `main`:
https://github.com/xamarin/XamarinComponents/blob/main/azure-pipelines.yml#L15-L19

Therefore it will never test your PR changes to YAML files.  (I do not know why it is set up this way 🤷‍♂️)

This commit breaks the Linux lane with:
```
Workload ID maui isn't supported on this platform.
```

As a result we can no longer publish anything out of this repository.  We need to figure out if these changes were actually needed, and if so, how can we work around it for Linux.

**Pull request merged**
