### PR TITLE
OkHttp3-4.3.1

### PR DESCRIPTION
**Pull request by antonioseric**

### CODE REVIEW

**Comment by tranb3r** [comment]
When is the nuget going to be released ?

**Comment by 4brunu** [comment]
I think it's not published yet.

**Comment by tranb3r** [comment]
What is the process to get the nuget published once the PR is merged ?

**Comment by 4brunu** [comment]
I don't know, maybe @mattleibow can help with that.

**Comment by mattleibow** [comment]
I think this was a typical case of me merging and then going to bed. If all goes well, people get alerts and they hit the button. But, seems a step failed, so nothing got sent out....
Anyway, did a rebuild and now they are out in the wild!!! Go moggy!

**Pull request merged**
