### PR TITLE
Update the Mono.DataConverter, Mono.Options, Mono.Terminal Libraries

### PR DESCRIPTION
**Pull request by mattleibow**

### CODE REVIEW

**Comment by mattleibow** [comment]
~Do not merge, waiting on https://github.com/mono/mono/pull/9556~

**Review by newky2k — DISMISSED** [review]
There are build issues when building samples for Mono.DataConverter -> https://gist.github.com/newky2k/6fe603b27a6df56cf2c3713846e0a6b4

**Comment by mattleibow** [comment]
@newky2k I think your packages may be corrupt... It appears to be downloading `Xamarin.Android.Support.v4 27.0.2.1`.

**Comment by mattleibow** [comment]
Fixes #174

**Review by newky2k — APPROVED** [review]

**Pull request merged**
