### PR TITLE
Kotlin 1.3.72

### PR DESCRIPTION
**Pull request by antonioseric**
This should be merged when #824 is merged and nuget `Xamarin.Kotlin.BindingSupport` version `0.7.0-preview` is published

### CODE REVIEW

**Comment by mattleibow** [comment]
I think this is a good time as any to see if we can drop the kotlin binding support nuget and use the new generator. Need to check which version of VS has it...

**Comment by antonioseric** [comment]
@mattleibow did you start with this? do you want me to checkout?
[Here](https://docs.microsoft.com/en-us/xamarin/android/platform/binding-kotlin-library/) is docs

**Comment by mattleibow** [comment]
Hey there @antonioseric! You can go right ahead. Sorry for taking months to get back to you.

I just closed the other PR now as I don't think we will be supporting that way much/any more. The built in tooling is actually much better than that fixups now. The diff might be quite big as the NuGet fix didn't get the visibilities right often. But, if there are some serious issues with the tooling, please open an issue https://github.com/xamarin/xamarin-android and ping me there. I'll make sure to get that team on it asap. Also, I might be able to help with workarounds and things like that.

**Comment by antonioseric** [comment]
@mattleibow i remove `Xamarin.Kotlin.BindingSupport` now it is buildin tooling. Can we also release 1.3.61 version?

**Comment by mattleibow** [comment]
@antonioseric I updated the 1.3.61 version in master to use the new tooling before I release. Do you have some real-world app/library that can test it out?

https://github.com/xamarin/XamarinComponents/pull/964

**EDIT**

I just see that you also did the same to your PR. 😆 

I'll merge mine then and release since the changes are the same. Have you tested your packages and confirm they work as expected? When I run my sample app in there, is teems to work, but I am not sure that is a totally useful test case.

You should be able to rebase once merged. If everything still works, then we can release 71 as well.

**Comment by 4brunu** [comment]
Could you please also add support for Kotlin 1.4.0?

**Comment by mattleibow** [comment]
@4brunu could you open an new issue so we can track this? 

I'd like to keep this PR for the last v1.3.x

**Comment by 4brunu** [comment]
Sorry, I opened https://github.com/xamarin/XamarinComponents/issues/965.

**Comment by mattleibow** [comment]
Thanks! I'll have a look and see what it takes to get that out soon. Unless @antonioseric already started on that?

**Review by mattleibow — APPROVED** [review]

**Comment by mattleibow** [comment]
@antonioseric thanks for the work on this and the other PRs. I have merged this and once CI is done, a release will go out 😄

**Pull request merged**
