### PR TITLE
[Estimote iOS] Update binding to 4.26.3

### PR DESCRIPTION
**Pull request by bholmes**

### CODE REVIEW

**Comment by michaeldimoudis** [comment]
Thanks @bholmes! I did the same for 4.26.3 but yours looks better and you updated the samples/documentation. Doing a quick test I could call SecureBeaconManager events (which are broken in the current nuget version), and I tested the MonitoringV2Manager on a real iOS device with new Estimote proximity beacons which worked great!

LGTM 👍

**Comment by bholmes** [comment]
@michaeldimoudis Thanks!  I am waiting for a review from @SotoiGhost as well.  I hope to get this merged and published soon.

**Comment by michaeldimoudis** [comment]
Should this PR also be updated from EstimoteSDK 4.26.2 to 4.26.3? Haven't checked but it might not even include any binding updates.

**Review by SotoiGhost — DISMISSED** [review]
LGTM, just added some missing classes and missing attributes, waiting for @bholmes review.

**Pull request merged**
