### PR TITLE
kotlinx-coroutines-1.5.1

### PR DESCRIPTION
**Pull request by 4brunu**
bump kotlinx coroutines to 1.5.1

### CODE REVIEW

**Comment by 4brunu** [comment]
This PR depends on https://github.com/xamarin/XamarinComponents/pull/1228

**Comment by 4brunu** [comment]
@moljac this one is also ready to review and merge now 🙂

**Review by moljac — APPROVED** [review]
LGTM

**Comment by 4brunu** [comment]
Thanks 👍

**Pull request merged**
