### PR TITLE
ARCore 1.24

### PR DESCRIPTION
**Pull request by softlion**
This PR upgrades ARCore to 1.24 from 1.23, and simplifies the binding to get the full power of ARCore.

### CODE REVIEW

**Comment by softlion** [comment]
Note that, for some reason, the proguard rules are not kept/used. Maybe because i'm referencing this nuget from a sdkextra project, which in turn is referenced by my android project ?

So solution: unzip the aar file, get the proguard file at its root, and copy it to your android app project and set the correct build property (ie: proguard rule).

**Comment by softlion** [comment]
While the component works correctly in most situations,  
when the android simulator's virtual ar is crashing (because it has bugs too) and when using hot reload,  
i stumble upon a suspicious crash. Is it a mono or compiler or hot reload issue ?  
It seems more an issue in the java arlib itself.

```
Google.AR.Core.Exceptions.FatalException
Unable to cast object of type 'Mono.Debugger.Soft.PointerValue' to type 'Mono.Debugger.Soft.PrimitiveValue'.


  --- End of managed Google.AR.Core.Exceptions.FatalException stack trace ---
com.google.ar.core.exceptions.FatalException
at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:16)
	at com.google.ar.core.Session.nativeUpdate(Native Method)
	at com.google.ar.core.Session.update(Session.java:2)
	at crc6473bfaa190056c7db.ArRender.n_onDrawFrame(Native Method)
	at crc6473bfaa190056c7db.ArRender.onDrawFrame(ArRender.java:39)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)


  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <94b04e1756104d1fa1d144932ae2720c>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a]
  at Google.AR.Core.Session.Update () [0x0000a] in <6d850c427ce84605a85725ce4ffa7c6f>:0 
  at ArRendererOnDrawFrame
(Javax.Microedition.Khronos.Opengles.IGL10 gl) [0x0001d] 
  at Android.Opengl.GLSurfaceView+IRendererInvoker.n_OnDrawFrame_Ljavax_microedition_khronos_opengles_GL10_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_gl) [0x00010] in /Users/builder/azdo/_work/278/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-30/mcw/Android.Opengl.GLSurfaceView.cs:578 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.212(intptr,intptr,intptr)

```

**Review by moljac — APPROVED** [review]
LGTM (after version fixes)

**Pull request merged**
