### PR TITLE
KotlinXCoroutines-1.4.3

### PR DESCRIPTION
**Pull request by moljac**
version bumps

### CODE REVIEW

**Comment by jpobst** [comment]
Note this removes a lot of types in `Xamarin.KotlinX.Coroutines.Core.dll`.  Please ensure this is intended.

[Xamarin.KotlinX.Coroutines.Core.dll.breaking.md](https://github.com/xamarin/XamarinComponents/files/6479173/Xamarin.KotlinX.Coroutines.Core.dll.breaking.md)

**Comment by moljac** [comment]
There are no `*.class` files in:

* `kotlinx-coroutines-core-1.4.3`
* `kotlinx-coroutines-core-1.5.0`

only `*.kotlin_metadata`

https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/api/kotlinx-coroutines-core.api

version 1.4.3 added dependency on `kotlinx-coroutines-core-jvm-1.4.3.jar` 

https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.4.3/kotlinx-coroutines-core-1.4.3.pom

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<!--  This module was also published with a richer model, Gradle metadata,   -->
<!--  which should be used instead. Do not delete the following line which   -->
<!--  is to indicate to Gradle or any Gradle module metadata file consumer   -->
<!--  that they should prefer consuming it instead.  -->
<!--  do_not_remove: published-with-gradle-metadata  -->
<modelVersion>4.0.0</modelVersion>
<groupId>org.jetbrains.kotlinx</groupId>
<artifactId>kotlinx-coroutines-core</artifactId>
<version>1.4.3</version>
<name>kotlinx-coroutines-core</name>
<description>Coroutines support libraries for Kotlin</description>
<url>https://github.com/Kotlin/kotlinx.coroutines</url>
<licenses>
<license>
<name>The Apache Software License, Version 2.0</name>
<url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
<distribution>repo</distribution>
</license>
</licenses>
<developers>
<developer>
<id>JetBrains</id>
<name>JetBrains Team</name>
<organization>JetBrains</organization>
<organizationUrl>https://www.jetbrains.com</organizationUrl>
</developer>
</developers>
<scm>
<url>https://github.com/Kotlin/kotlinx.coroutines</url>
</scm>
<dependencies>
<dependency>
<groupId>org.jetbrains.kotlinx</groupId>
<artifactId>kotlinx-coroutines-core-jvm</artifactId>
<version>1.4.3</version>
<scope>compile</scope>
</dependency>
</dependencies>
<packaging>pom</packaging>
</project>
```

**Comment by moljac** [comment]
```
#### Removed Type Xamarin.KotlinX.Coroutines.AwaitKt
#### Removed Type Xamarin.KotlinX.Coroutines.BuildersKt
#### Removed Type Xamarin.KotlinX.Coroutines.CancellableContinuationDefaultImpls
#### Removed Type Xamarin.KotlinX.Coroutines.CancellableContinuationImplKt
#### Removed Type Xamarin.KotlinX.Coroutines.CancellableContinuationKt
#### Removed Type Xamarin.KotlinX.Coroutines.CompletableDeferredKt
#### Removed Type Xamarin.KotlinX.Coroutines.CompletionHandlerException
#### Removed Type Xamarin.KotlinX.Coroutines.CompletionHandlerKt
#### Removed Type Xamarin.KotlinX.Coroutines.CompletionHandler_commonKt
#### Removed Type Xamarin.KotlinX.Coroutines.CompletionStateKt
#### Removed Type Xamarin.KotlinX.Coroutines.CoroutineContextKt
#### Removed Type Xamarin.KotlinX.Coroutines.CoroutineDispatcher
#### Removed Type Xamarin.KotlinX.Coroutines.CoroutineExceptionHandler
#### Removed Type Xamarin.KotlinX.Coroutines.CoroutineExceptionHandlerDefaultImpls
#### Removed Type Xamarin.KotlinX.Coroutines.CoroutineExceptionHandlerImplKt
#### Removed Type Xamarin.KotlinX.Coroutines.CoroutineExceptionHandlerKey
#### Removed Type Xamarin.KotlinX.Coroutines.CoroutineExceptionHandlerKt
#### Removed Type Xamarin.KotlinX.Coroutines.CoroutineName
#### Removed Type Xamarin.KotlinX.Coroutines.CoroutineScopeKt
#### Removed Type Xamarin.KotlinX.Coroutines.CoroutineStart
#### Removed Type Xamarin.KotlinX.Coroutines.DebugKt
#### Removed Type Xamarin.KotlinX.Coroutines.DebugStringsKt
#### Removed Type Xamarin.KotlinX.Coroutines.DefaultExecutorKt
#### Removed Type Xamarin.KotlinX.Coroutines.DelayDefaultImpls
#### Removed Type Xamarin.KotlinX.Coroutines.DelayKt
#### Removed Type Xamarin.KotlinX.Coroutines.DispatchedTaskKt
#### Removed Type Xamarin.KotlinX.Coroutines.Dispatchers
#### Removed Type Xamarin.KotlinX.Coroutines.DispatchersKt
#### Removed Type Xamarin.KotlinX.Coroutines.EventLoopKt
#### Removed Type Xamarin.KotlinX.Coroutines.EventLoop_commonKt
#### Removed Type Xamarin.KotlinX.Coroutines.ExceptionsKt
#### Removed Type Xamarin.KotlinX.Coroutines.ExecutorCoroutineDispatcher
#### Removed Type Xamarin.KotlinX.Coroutines.ExecutorsKt
#### Removed Type Xamarin.KotlinX.Coroutines.ExperimentalCoroutinesApiAttribute
#### Removed Type Xamarin.KotlinX.Coroutines.FlowPreviewAttribute
#### Removed Type Xamarin.KotlinX.Coroutines.GlobalScope
#### Removed Type Xamarin.KotlinX.Coroutines.ICancellableContinuation
#### Removed Type Xamarin.KotlinX.Coroutines.ICopyableThrowable
#### Removed Type Xamarin.KotlinX.Coroutines.ICoroutineExceptionHandler
#### Removed Type Xamarin.KotlinX.Coroutines.ICoroutineScope
#### Removed Type Xamarin.KotlinX.Coroutines.IDelay
#### Removed Type Xamarin.KotlinX.Coroutines.IDisposableHandle
#### Removed Type Xamarin.KotlinX.Coroutines.IExperimentalCoroutinesApi
#### Removed Type Xamarin.KotlinX.Coroutines.IFlowPreview
#### Removed Type Xamarin.KotlinX.Coroutines.IInternalCoroutinesApi
#### Removed Type Xamarin.KotlinX.Coroutines.IObsoleteCoroutinesApi
#### Removed Type Xamarin.KotlinX.Coroutines.IThreadContextElement
#### Removed Type Xamarin.KotlinX.Coroutines.InternalCoroutinesApiAttribute
#### Removed Type Xamarin.KotlinX.Coroutines.InterruptibleKt
#### Removed Type Xamarin.KotlinX.Coroutines.JobKt
#### Removed Type Xamarin.KotlinX.Coroutines.JobSupportKt
#### Removed Type Xamarin.KotlinX.Coroutines.MainCoroutineDispatcher
#### Removed Type Xamarin.KotlinX.Coroutines.NonCancellable
#### Removed Type Xamarin.KotlinX.Coroutines.NonDisposableHandle
#### Removed Type Xamarin.KotlinX.Coroutines.ObsoleteCoroutinesApiAttribute
#### Removed Type Xamarin.KotlinX.Coroutines.RunnableKt
#### Removed Type Xamarin.KotlinX.Coroutines.SchedulerTaskKt
#### Removed Type Xamarin.KotlinX.Coroutines.SupervisorKt
#### Removed Type Xamarin.KotlinX.Coroutines.ThreadContextElementDefaultImpls
#### Removed Type Xamarin.KotlinX.Coroutines.ThreadContextElementKt
#### Removed Type Xamarin.KotlinX.Coroutines.ThreadPoolDispatcherKt
#### Removed Type Xamarin.KotlinX.Coroutines.TimeSourceKt
#### Removed Type Xamarin.KotlinX.Coroutines.TimeoutCancellationException
#### Removed Type Xamarin.KotlinX.Coroutines.TimeoutKt
#### Removed Type Xamarin.KotlinX.Coroutines.YieldKt
### Removed Namespace Xamarin.KotlinX.Coroutines.Channels


#### Removed Type Xamarin.KotlinX.Coroutines.Channels.AbstractChannelKt
#### Removed Type Xamarin.KotlinX.Coroutines.Channels.ActorKt
#### Removed Type Xamarin.KotlinX.Coroutines.Channels.BroadcastChannelKt
#### Removed Type Xamarin.KotlinX.Coroutines.Channels.BroadcastKt
#### Removed Type Xamarin.KotlinX.Coroutines.Channels.BufferOverflow
#### Removed Type Xamarin.KotlinX.Coroutines.Channels.ChannelIteratorDefaultImpls
#### Removed Type Xamarin.KotlinX.Coroutines.Channels.ChannelKt
#### Removed Type Xamarin.KotlinX.Coroutines.Channels.ChannelsKt
#### Removed Type Xamarin.KotlinX.Coroutines.Channels.ClosedReceiveChannelException
#### Removed Type Xamarin.KotlinX.Coroutines.Channels.ClosedSendChannelException
#### Removed Type Xamarin.KotlinX.Coroutines.Channels.ConflatedBroadcastChannel
#### Removed Type Xamarin.KotlinX.Coroutines.Channels.IChannelIterator
#### Removed Type Xamarin.KotlinX.Coroutines.Channels.ProduceKt
#### Removed Type Xamarin.KotlinX.Coroutines.Channels.TickerChannelsKt
#### Removed Type Xamarin.KotlinX.Coroutines.Channels.TickerMode
#### Removed Type Xamarin.KotlinX.Coroutines.Channels.ValueOrClosed
### Removed Namespace Xamarin.KotlinX.Coroutines.Flow


#### Removed Type Xamarin.KotlinX.Coroutines.Flow.FlowKt
#### Removed Type Xamarin.KotlinX.Coroutines.Flow.IFlow
#### Removed Type Xamarin.KotlinX.Coroutines.Flow.IFlowCollector
#### Removed Type Xamarin.KotlinX.Coroutines.Flow.IMutableSharedFlow
#### Removed Type Xamarin.KotlinX.Coroutines.Flow.IMutableStateFlow
#### Removed Type Xamarin.KotlinX.Coroutines.Flow.ISharedFlow
#### Removed Type Xamarin.KotlinX.Coroutines.Flow.ISharingStarted
#### Removed Type Xamarin.KotlinX.Coroutines.Flow.IStateFlow
#### Removed Type Xamarin.KotlinX.Coroutines.Flow.LintKt
#### Removed Type Xamarin.KotlinX.Coroutines.Flow.SharedFlowKt
#### Removed Type Xamarin.KotlinX.Coroutines.Flow.SharingCommand
#### Removed Type Xamarin.KotlinX.Coroutines.Flow.SharingStarted
#### Removed Type Xamarin.KotlinX.Coroutines.Flow.SharingStartedCompanion
#### Removed Type Xamarin.KotlinX.Coroutines.Flow.SharingStartedKt
#### Removed Type Xamarin.KotlinX.Coroutines.Flow.StateFlowKt
### Removed Namespace Xamarin.KotlinX.Coroutines.Intrinsics


#### Removed Type Xamarin.KotlinX.Coroutines.Intrinsics.CancellableKt
#### Removed Type Xamarin.KotlinX.Coroutines.Intrinsics.UndispatchedKt
### Removed Namespace Xamarin.KotlinX.Coroutines.Scheduling


#### Removed Type Xamarin.KotlinX.Coroutines.Scheduling.CoroutineSchedulerKt
#### Removed Type Xamarin.KotlinX.Coroutines.Scheduling.ExperimentalCoroutineDispatcher
#### Removed Type Xamarin.KotlinX.Coroutines.Scheduling.TasksKt
#### Removed Type Xamarin.KotlinX.Coroutines.Scheduling.WorkQueueKt
### Removed Namespace Xamarin.KotlinX.Coroutines.Selects


#### Removed Type Xamarin.KotlinX.Coroutines.Selects.SelectKt
#### Removed Type Xamarin.KotlinX.Coroutines.Selects.SelectUnbiasedKt
#### Removed Type Xamarin.KotlinX.Coroutines.Selects.WhileSelectKt
### Removed Namespace Xamarin.KotlinX.Coroutines.Sync


#### Removed Type Xamarin.KotlinX.Coroutines.Sync.ISemaphore
#### Removed Type Xamarin.KotlinX.Coroutines.Sync.MutexKt
#### Removed Type Xamarin.KotlinX.Coroutines.Sync.SemaphoreKt
### Removed Namespace Xamarin.KotlinX.Coroutines.Test


#### Removed Type Xamarin.KotlinX.Coroutines.Test.TestCoroutineContextKt
```

those were moved to

```
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.JobKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.JobSupportKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.IThreadContextElement.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Channels.ActorKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.CoroutineScopeKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Channels.BroadcastChannelKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.IChildHandle.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Channels.TickerMode.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.TimeSourceKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Sync.ISemaphore.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.AwaitKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.TimeoutKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.ExceptionsKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Channels.IChannelIterator.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Test.TestCoroutineContext.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.DefaultExecutorKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.CoroutineExceptionHandlerKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.DelayKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Channels.BroadcastKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.CoroutineExceptionHandlerImplKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.FlowPreviewAttribute.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.ICancellableContinuation.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.CoroutineStart.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.CoroutineDispatcher.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Channels.ChannelKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.CoroutineName.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Dispatchers.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Flow.IMutableStateFlow.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Scheduling.WorkQueueKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.CancellableContinuationImplKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Scheduling.TasksKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.ExecutorsKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Flow.IFlowCollector.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.ICoroutineExceptionHandler.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.ThreadContextElementKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Channels.AbstractChannelKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.EventLoopKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Channels.ValueOrClosed.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Flow.SharedFlowKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.SupervisorKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.ICoroutineScope.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Channels.TickerChannelsKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Flow.IStateFlow.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.CoroutineContextKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Sync.SemaphoreKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.InterruptibleKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Intrinsics.UndispatchedKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Channels.BufferOverflow.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Channels.ChannelsKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.EventLoop_commonKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.InternalCoroutinesApiAttribute.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.IInternalCoroutinesApi.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Selects.SelectUnbiasedKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Flow.IFlow.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Selects.SelectKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Flow.IMutableSharedFlow.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Flow.ISharedFlow.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Channels.ProduceKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.ICopyableThrowable.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/__NamespaceMapping__.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.MainCoroutineDispatcher.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.ExperimentalCoroutinesApiAttribute.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.DispatchedTaskKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Sync.MutexKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Scheduling.CoroutineSchedulerKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.CompletionStateKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Flow.SharingCommand.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Java.Interop.__TypeRegistrations.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.NonDisposableHandle.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.TimeoutCancellationException.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.CompletionHandler_commonKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.YieldKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.DispatchersKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Scheduling.ExperimentalCoroutineDispatcher.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.CompletionHandlerException.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.CompletionHandlerKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Channels.ClosedReceiveChannelException.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Selects.WhileSelectKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Flow.SharingStartedKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.IObsoleteCoroutinesApi.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.CompletableDeferredKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.IExperimentalCoroutinesApi.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.ThreadPoolDispatcherKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Channels.ConflatedBroadcastChannel.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.NonCancellable.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Intrinsics.CancellableKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.ObsoleteCoroutinesApiAttribute.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Flow.FlowKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.IDelay.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.IFlowPreview.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.JobSupport.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.DebugStringsKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.DebugKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.GlobalScope.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Flow.LintKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.RunnableKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Flow.ISharingStarted.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Flow.StateFlowKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.ExecutorCoroutineDispatcher.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Channels.ClosedSendChannelException.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.Test.TestCoroutineContextKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.CancellableContinuationKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.SchedulerTaskKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.IDisposableHandle.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//generated/src/Xamarin.KotlinX.Coroutines.BuildersKt.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//KotlinX.Coroutines.Core.Jvm.AssemblyInfo.cs
./source/KotlinX.Coroutines.Core.Jvm/obj/Debug/monoandroid9.0//MonoAndroid,Version=v9.0.AssemblyAttributes.cs
```

**Comment by moljac** [comment]
Added:

```
 <ItemGroup>
    <ProjectReference Include="..\KotlinX.Coroutines.Core.Jvm\KotlinX.Coroutines.Core.Jvm.csproj" />
  </ItemGroup>
```
to `KotlinX.Coroutines.Core.Jvm\KotlinX.Coroutines.Core.csproj`

https://github.com/xamarin/XamarinComponents/blob/KotlinXCoroutines-1.4.3/Android/KotlinXCoroutines/source/KotlinX.Coroutines.Core/KotlinX.Coroutines.Core.csproj#L56

which produces correct `nuspec`:

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Xamarin.KotlinX.Coroutines.Core</id>
    <version>1.4.3</version>
    <title>Xamarin.KotlinX.Coroutines.Core reference library for Xamarin.Android</title>
    <authors>Microsoft</authors>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <license type="file">LICENSE.md</license>
    <licenseUrl>https://aka.ms/deprecateLicenseUrl</licenseUrl>
    <projectUrl>https://go.microsoft.com/fwlink/?linkid=2083771</projectUrl>
    <description>Xamarin.Android bindings for KotlinX.Coroutines.Core</description>
    <copyright>© Microsoft Corporation. All rights reserved.</copyright>
    <dependencies>
      <group targetFramework="MonoAndroid9.0">
        <dependency id="Xamarin.KotlinX.Coroutines.Core.Jvm" version="1.4.3" exclude="Build,Analyzers" />
        <dependency id="Xamarin.Kotlin.StdLib" version="1.4.32.1" exclude="Build,Analyzers" />
        <dependency id="Xamarin.Kotlin.StdLib.Common" version="1.4.32.1" exclude="Build,Analyzers" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="Java.Interop" targetFramework="MonoAndroid9.0" />
    </frameworkAssemblies>
  </metadata>
</package>```

**Review by jpobst — APPROVED** [review]

**Pull request merged**
