### PR TITLE
SignalR-6.0.0

### PR DESCRIPTION
**Pull request by 4brunu**
Update SignalR Java Client to 6.0.0

### CODE REVIEW

**Review by moljac — APPROVED** [review]
LGTM

**Comment by 4brunu** [comment]
@moljac Hey, 
This package update is not published yet on nugget, did it failed?
Thanks

**Comment by moljac** [comment]
it was tagged

https://github.com/xamarin/XamarinComponents/releases/tag/SignalR.Java.Client-6.0.0-20211121

now I have to dig deeper

**Comment by moljac** [comment]
publishing conflict - 5.0.10. I bet I messed something up with conflict resolving the merging

```
2021-11-21T13:27:14.8427452Z Pushing Xamarin.AspNet.SignalR.Java.Client.5.0.10.nupkg to 'https://www.nuget.org/api/v2/package'...
2021-11-21T13:27:14.8428693Z   PUT https://www.nuget.org/api/v2/package/
2021-11-21T13:27:14.8429738Z   Conflict https://www.nuget.org/api/v2/package/ 282ms
2021-11-21T13:27:14.8431083Z Package 'D:\a\r1\a\tempsigned\Xamarin.AspNet.SignalR.Java.Client.5.0.10.nupkg' already exists at feed 'https://www.nuget.org/api/v2/package'.
2021-11-21T13:27:14.8517751Z ##[section]Finishing: NuGet custom push
```

**Comment by moljac** [comment]
nope

it is 6.0.0

https://github.com/xamarin/XamarinComponents/blob/main/Android/SignalRJavaClient/source/SignalR.Java.Client/SignalR.Java.Client.csproj#L25

**Comment by moljac** [comment]
retagged
waiting for CI

**Comment by 4brunu** [comment]
Thanks, it worked 👍

**Pull request merged**
