### PR TITLE
Square.Retrofit2.ConverterMoshi 2.9.0

### PR DESCRIPTION
**Pull request by antonioseric**

### CODE REVIEW

**Review by moljac — APPROVED** [review]
LGTM
thanks

**Review by moljac — APPROVED** [review]
LGTM

fala

**Comment by antonioseric** [comment]
@moljac package is not published to [nuget.org ](https://www.nuget.org/packages/Square.Retrofit2.ConverterMoshi/) can you please check

**Comment by humblehacker** [comment]
@moljac Can we please have this published to [nuget.org](https://www.nuget.org/packages/Square.Retrofit2.ConverterMoshi/)? 🙏

**Comment by moljac** [comment]
not sure what happened 
it was tagged SquareRetrofit2ConverterMoshi-2.9.0-20220316
let me try again

**Pull request merged**
