### PR TITLE
Make the properties of the OfflinePackProgress struct public so they …

### PR DESCRIPTION
**Pull request by WiredUK**
…can be used

### CODE REVIEW

**Comment by WiredUK** [comment]
Fixing [issue 84](https://github.com/xamarin/XamarinComponents/issues/84)

**Review by newky2k — CHANGES_REQUESTED** [review]
Android source, at least is not compiling ->
https://gist.github.com/newky2k/7ab69a22a182f6c67382d5497e4313f6

**Comment by WiredUK** [comment]
@newky2k I'm confused about a couple of things on this one. First of all the fact it doesn't compile when all I did was make some struct properties public. Secondly the gist you added states that Android is not compiling when the change I made was for the iOS code only. Colour me baffled! :)

**Comment by newky2k** [comment]
@WiredUK  Hi,  I'm not suggesting your code is the cause of the failure just that overall, in its current state the component doesn't compile, and someone from the xamarin team will need to investigate before it can be merged

**Pull request merged**
