### PR TITLE
[SlackTextViewController] Updated to (almost) v1.9.6 to fix iOS 11 bugs

### PR DESCRIPTION
**Pull request by mattleibow**
This addresses https://github.com/xamarin/XamarinComponents/issues/244

This build works off a specific commit due to the version not being out yet, and this is a critical fix.

### CODE REVIEW

**Comment by softwaremills** [comment]
Thank you very much, sir!

**Comment by mattleibow** [comment]
Because the native version is not yet released, this will be a preview release. As soon as the official version goes out, we will release the new version with any additional fixes/features.

**Comment by softwaremills** [comment]
That seems eminently reasonable.

**Comment by bholmes** [comment]
fyi...   https://www.nuget.org/packages/Xamarin.SlackTextViewController/1.9.6-preview

**Comment by uhw76tgwquerhjbqwnejk** [comment]
does this fix the inserting/deleting cells issue?

**Comment by softwaremills** [comment]
I'm not sure if it fixes that, but I have tested it and it does fix the problem where on iOS 11 the spacing at the bottom was all wrong and the text field didn't register taps. Thank you very much @mattleibow and @bholmes !

**Comment by mattleibow** [comment]
Great to hear that it fixes the iOS 11 issue. Any other issues need to be logged against the native library as this is just the binding.

**Pull request merged**
