### PR TITLE
SquareOkHttpUrlConnection-4.3.1

### PR DESCRIPTION
**Pull request by antonioseric**

### CODE REVIEW

**Comment by tranb3r** [comment]
@antonioseric @mattleibow 
What is blocking this PR ?
Now that okhttp 4.3.1 nuget has been published, it would be great to publish this one as well.
Thank you !

**Comment by tranb3r** [comment]
@antonioseric @mattleibow 
Any update on this ? Thanks

**Review by moljac — APPROVED** [review]
Thanks!
Fala!

**Review by moljac — APPROVED** [review]
Thanks!
Fala!

**Pull request merged**
