### PR TITLE
Coil-1.3.2

### PR DESCRIPTION
**Pull request by 4brunu**
This package together with https://github.com/xamarin/XamarinComponents/pull/1250 allows Xamarin Android apps que use Coil as image loading.
Coil is becoming increasingly popular in Android, and with the arrival of Jetpack Compose, Coil is the only one that officially supports it, and it's being recommended by google employees.

### CODE REVIEW

**Review by moljac — CHANGES_REQUESTED** [review]
please provide some description in PR description field

I (we) need it to know what is about (for priorities 😄 )

**Comment by 4brunu** [comment]
Sorry about that, I have updated the description and will update it from now on 🙂

**Comment by moljac** [comment]
> Sorry about that, I have updated the description and will update it from now on 🙂

no need to be sorry. You cannot know it all... muito obrigado

**Comment by 4brunu** [comment]
You will learn Portuguese from all my PR's that you review! 😃

De nada!

**Comment by moljac** [comment]
> You will learn Portuguese from all my PR's that you review! 😃

I wish. I have Roman languages (Portugese, Spanish, French, Italian) on my list, but never had time for them. I learned a bit Portugese when I was on Cabo Verde for windsurfing during honeymoon. That was beautiful.  

BTW I will merge this as soon as I fix CI

**Comment by 4brunu** [comment]
@moljac bom dia! Dobro jutro! I think CI is now passing 🙂

**Comment by 4brunu** [comment]
@moljac since I merged the master branch, CI is failing, but I don't know why.
Can you please help with this?
Thanks

**Comment by 4brunu** [comment]
CI is now passing again, thanks

**Review by moljac — APPROVED** [review]
LGTM

**Pull request merged**
