### PR TITLE
kotlinx-coroutines-1.5.2

### PR DESCRIPTION
**Pull request by 4brunu**
bump kotlinx coroutines to 1.5.2

### CODE REVIEW

**Review by moljac — APPROVED** [review]
LGTM

this will most likely move to AndroidX or GPS-FB-MLKIT repo

**Comment by 4brunu** [comment]
Maybe this can be closed in favor of https://github.com/xamarin/AndroidX/pull/370?

**Comment by moljac** [comment]
no. it is OK. We'll publish it from here. I need to review AndroidX and I have small hiccups with weekly stable updates there

**Comment by 4brunu** [comment]
Hey, this nuget package didn't get updated, anything went wrong?

**Pull request merged**
